### ISSUE TITLE
Multiple Database Providers

### ISSUE THREAD

**Issue by jonreis** [jonwagner/Insight.Database#127]
Just a question.

Is it possible to have 2 database providers going at the same time? Say read from a SqlServer database and write to a Postgres one.

Thanks for the great library Jon!

Jonathan

**Comment by jonreis** [comment]
Hey Jon,
do you have a PayPal account? I would like to send you a beer, or 10.

Jonathan

**Comment by jonwagner** [comment]
Sure thing!

Send me a direct email to my hotmail account (jonwagner) and I'll send you the info. Thanks for your support!
