### ISSUE TITLE
ReliableConnection is not compatible with OpenWithTransaction

### ISSUE THREAD

**Issue by Sprinkle** [jonwagner/Insight.Database#180]
Cannot use ReliableConnection with the OpenWithTransaction extension.

The following throws "ExecuteReader requires the command to have a transaction when the connection assigned to the command is in a pending local transaction.  The Transaction property of the command has not been initialized."

var sqlConnection = new SqlConnection();
var reliable = new ReliableConnection(sqlConnection);
using (var conn = reliable.OpenWithTransaction())
{
        var ret = conn.QuerySql(@"SELECT 1", Query.Returns(OneToOne<int>.Records));
}

**Comment by jonwagner** [comment]
This will be fixed in v5.2.1
