### ISSUE TITLE
issue with connection + transaction

### ISSUE THREAD

**Issue by hgjura** [jonwagner/Insight.Database#181]
Hello 

I am trying to open a conn + transaction in the following form:
using (var db = (new SqlConnection(ManualConnectionString))).OpenWithTransaction()) {...}

but I receive errors. It seems this extension is available only with ConnectionStringSetting.

If it exists, what would be the usage of OpenWithTransaction() with a SqlConnection object.

Thanks.

**Comment by kevinsea** [comment]
Hi, I think you might just be missing this the top of the file:

using Insight.Database;

The extension methods won't work without this.

**Comment by jonwagner** [comment]
Kevin is right. There's a version of OpenWithTransaction that works with an IDbConnection. You just need the using statement. Let me know if that doesn't work for you.
