### ISSUE TITLE
Expose Type Member Cache

### ISSUE THREAD

**Issue by DamianReeves** [jonwagner/Insight.Database#184]
If you end up writing a custom mapper (i.e. a IParameterMapper), you may need to check the type to see if it contains the property you are trying to map to, or maybe you need to look up member information for the type in some way.

With that in mind I think it makes sense to expose `ClassPropInfo` or some of its API surface when performing mapping so we don't incur the cost of reflecting twice. Allow us to use the cache you already maintain for search capabilities.

**Comment by jonwagner** [comment]
I'd rather not expose all of `ClassPropInfo`. It's pretty complex and likely to change from version to version.

Note that parameter mapping is only done once for each unique CommandText, and the results are cached, so you're not going to see a big performance hit from doing any additional reflection.

That being said, if we talk through some use cases, we probably can come up with something that at least makes the code easier/prettier.

**Comment by DamianReeves** [comment]
I agree exposing ClassPropInfo is probably not ideal or needed. Maybe if you add an extension member method to IParameterMapper that uses ClassPropInfo for member lookup that would be sufficient.

My main usecase is trying to apply conventions that are used in most cases but not in some. For example all stored procs in a database I am working with have underscores (i.e. package_name), I'd like to use .NET conventions and map that to PackageName (which I've done in code), but for safety I'd like my "UnderscoreToCamelCaseParameterMapper" to ensure the property/member exists on the type before choosing to return the new mapped name. This is where it would be nice to use the cache you already have.

I also find myself not using auto interface implementation in some cases because I don't want to expose parameter names with underscores. I end up writing out the calls to Execute and Query by hand (which is still pretty short thanks to Insight), but I think it would be nice if you added a ParameterNameAttribute which could be used for inline parameter name mapping right on interfaces. If you don't implement it then I'd do that and use reflection but once again I'd want to use your reflection cache.

Thoughts?

**Comment by jonwagner** [comment]
I just pushed up code that lets you put a ColumnAttribute on interface parameters, like:

    IList<Foo> QueryBlah([Column("foo")] int goo);

It would also support overriding the serialization mode, etc. if you needed to do that. It will be in the next build, which I'll probably do next week.

As for caching reflection calls, have you done any performance testing to see if it's a real issue?

**Comment by DamianReeves** [comment]
No I haven't done any performance testing in the reflection calls,
To be honest, the change you just pushed should address my needs.

**Comment by jonwagner** [comment]
v5.2.1 now has this feature.

**Comment by DamianReeves** [comment]
Thanks. Been using this and it works great.
