### ISSUE TITLE
Named parameters in the SQL (Text) methods with ODBC provider

### ISSUE THREAD

**Issue by dhinz** [jonwagner/Insight.Database#185]
I can't seem to get queries using named parameters to work with ODBC.

I'm using Sybase ASA 12.0.1 (not ASE!) with the respective ODBC database driver.
The database always returns an error (column x not found).

Any ideas on what I'm doing wrong?

    var bel = new it_bel
    {
        typ = 2,
        nr = itBelNr,
        pers_typ = (Int32)besteller["pers_typ"],
        pers_nr = (Int32)besteller["pers_nr"],
        status = "A",
        datum = DateTime.Now,
        adr1name1 = details.shipping_address.company,
        adr1name2 = details.shipping_address.firstname + ' ' + details.shipping_address.lastname,
        adr1zeile1 = details.shipping_address.street,
        adr1plz = details.shipping_address.postcode,
        adr1ort = details.shipping_address.city,
        adr1land = order.shipping_address_id,
        laender_kz = laender_kz,
        it_pers_online_id = order.customer_id,
        it_bel_online_id = order.order_id
    };

    con.InsertSql("INSERT INTO it_bel(typ, nr, pers_typ, pers_nr, status, datum, adr1name1, adr1name2, adr1zeile1, adr1plz, adr1ort, adr1land, laender_kz, it_pers_online_id, it_bel_online_id) " +
                    "            VALUES(@typ, @nr, @pers_typ, @pers_nr, @status, @datum, @adr1name1, @adr1name2, @adr1zeile1, @adr1plz, @adr1ort, @adr1land, @laender_kz, @it_pers_online_id, @it_bel_online_id)", bel);

**Comment by jonwagner** [comment]
I never realized this, but when using ODBC, .NET doesn't support using named parameters. See http://stackoverflow.com/questions/6338139/can-odbc-parameter-place-holders-be-named

I do think that I can update Insight to take care of this automatically, but I'll have to do some code...

**Comment by dhinz** [comment]
That issue is one of the reasons I tried using Insight ;-)

I'll use a workaround for now, but I'd really appreciate if Insight supported this in the future. It's a great project!

**Comment by jonwagner** [comment]
It's definitely doable. Probably not hard either.

**Comment by jonwagner** [comment]
Well, that wasn't so hard...Now to clean up the code...

**Comment by jonwagner** [comment]
I pushed up code with this fix in it, for the next build.

**Comment by dhinz** [comment]
Thanks, works like a charm :-)

But you might want to describe how to set up a build environment for this some time in the future, I couldn't figure out how to get this to work using your build script.

**Comment by jonwagner** [comment]
I have a building.txt file somewhere, but it's probably out of date. I also probably need to add an option to build without tests, because nobody else is going to set up a VM with 8 different database servers on it...

**Comment by jonwagner** [comment]
This is now in v5.2.1.
