### ISSUE TITLE
Mock InsightDbProvider

### ISSUE THREAD

**Issue by hvidgaard** [jonwagner/Insight.Database#186]
Hi,

I am trying to validate the mapping done by Insight to prevent against programming errors on our end and changed behaviour in Insight with newer versions. So what I wanted, was to make my own implementation of an InsightDbProvider where it react to the calls Insight makes. In our case it would be specific SPs that are called and the parameters that are passed, then return the resultset as expected from the DB, and throw an exception when raw sql is used. It does not seem like it is possible in the current state, unless I implement/mock a lot of classes from System.Data.

Can you say if it is reasonable to do, and in that case where would I have to start?

**Comment by jonwagner** [comment]
If you want to do a custom provider, I'd look at something like this:

* Derive from WrappedInsightDbProvider - mostly just to manage your own connection/command types. It could be as simple as the MiniProfiler provider implementation.
* Derive from DbConnectionWrapper and DbCommandWrapper. Those classes are designed to let you override just a few methods.

Then if you implement DbCommandWrapper's executeXYZ methods, you could probably accomplish your goals.

**Comment by jonwagner** [comment]
I'm going to close this one out. Let me know if you have any more questions.
