### ISSUE TITLE
Use in medium trust level

### ISSUE THREAD

**Issue by MicheleZelando** [jonwagner/Insight.Database#187]
Hi,
we are using Insight Database for our products and we are satisfied with it. However we need to load our web application on our client hosting service that has its security trust level set to medium and it cannot be overwritten using the related setting in web.config. Being unable to run it in full trust, the only remaining choice is to drop the use of Insight Database, a solution that we would like to avoid.

The actual error is the following:
"System.Security.SecurityException: Request for the permission of type 'System.Security.Permissions.ReflectionPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed."

Have you had previous experience with this kind of issue or can share with us some advice to work this around? Is there a way to make it work in medium trust setting?

Thanks
Regards

**Comment by jonwagner** [comment]
Insight uses a lot of dynamic code generation, which is usually prohibited in medium-trust environments. I don't think there's a way around that.

**Comment by MicheleZelando** [comment]
Thank you for your fast reply. It's unfortunate, but at least we now know that there's nothing we can do about it (apart avoiding that kind of hosting service when possible).
