### ISSUE TITLE
Old .Net 4.0 assembly in the latest Insight.Database.Json nuget package

### ISSUE THREAD

**Issue by DanPristupov** [jonwagner/Insight.Database#188]
Hi Jon,

I noticed that the latest Insight.Database.Json package (Insight.Database.Json.5.2.1) contains outdated .Net 4.0 assembly (4.2.2.0).
Here's the screen shot: http://glui.me/?i=9fgteen7t5hdvh5/2015-01-30_at_11.58_2x.png/

Hope you Insight.Database still supports .Net 4.0 :)

Thanks

**Comment by jonwagner** [comment]
Yikes! Must be some error in the build script. I'll take a look.

**Comment by jonwagner** [comment]
I fixed this. Now I just need to do a build.

**Comment by DanPristupov** [comment]
Cool. We'll get .Net 4.0 support again :).

Thank you.

**Comment by jonwagner** [comment]
I'll plan to do a build next week. Let me know if you need something sooner

**Comment by DanPristupov** [comment]
No, it's OK. Don't rush.

Thanks for making I.D.

**Comment by jonwagner** [comment]
This fix is in 5.2.2, in nuget.
