### ISSUE TITLE
MS Access driver 64 bit

### ISSUE THREAD

**Issue by ivoloshin** [jonwagner/Insight.Database#191]
Please forgive me if this is the wrong forum to ask this, but I'm looking for a bit of advice...

We've used Insight.Database ODBC connection object in .NET with great success thus far to connect to our legacy Access databases to pull in data. We do, however, now have a requirement to upgrade to 64 bit and yet still be able to pull data from Access. Unfortunately, I do not seem to find a good answer as to which connection object I could use that would provide 64 bit connection that would would work with Insight's code we already built.

Thank you,
Ilya

**Comment by jonwagner** [comment]
This is an excellent place to ask questions!

I haven't tried to get Insight to work with 64-bit Access ODBC. Insight should work fine with any ODBC driver, but from what I've read, it may be tricky to get it set up.

It looks like you'll need to something like this:

* Install the 64-bit Microsoft Access 2013 Runtime from http://www.microsoft.com/en-us/download/details.aspx?id=39358
* Use the right connection string. I think it's:
    * Driver={{Microsoft Access Driver (*.mdb, *.accdb)}};Dbq=%FILE_NAME%;Uid=Admin;Pwd=;
    * This article might help: http://stackoverflow.com/questions/6954803/alternative-to-microsoft-jet-oledb-4-0-for-64-bit-access-on-mdb-file


Let me know if that works for you.

**Comment by ivoloshin** [comment]
Thank you for the reply. I'll give this a try and let you know!

**Comment by ivoloshin** [comment]
Jon,

After installing the drivers you've linked and some testing we have an answer that works. Here's the connection string we used:

```
var connectionString = string.Format("Provider=Microsoft.ACE.OLEDB.12.0;Data Source={0};", databasePath);
```

And we used `new OleDbConnection` object to read the data it seems to have worked.

Thanks again,
Ilya

**Comment by jonwagner** [comment]
Enjoy!
