### ISSUE TITLE
Postgresql JSON datatype support

### ISSUE THREAD

**Issue by AjmalVh** [jonwagner/Insight.Database#194]
I am using Postgresql 9.4 with [Json datatype](http://www.postgresql.org/docs/9.4/static/datatype-json.html) and I am looking for a .NET micro ORM which supports Json datatype. Does Insight.PostgreSQL provider support this datatype ?

**Comment by jonwagner** [comment]
It looks like I need to upgrade Npgsql to v2.2 or later, and possibly make some minor changes to Insight.

If you can provide some sample SQL (tables, procs & queries), I'll do the work on my end. It shouldn't be too difficult.

**Comment by AjmalVh** [comment]
Here is my table:

```sql
CREATE TABLE "User"
(
  "Id" integer NOT NULL, 
  "Email" text,
  "Country" text,
  "Company" text,
  "LastLogin" timestamp without time zone,
  "CreatedDate" timestamp without time zone,
  "OtherData" jsonb, -- All other user data
  CONSTRAINT "User_pkey" PRIMARY KEY ("Id")
)
```

The POCO  to map with:

```
public class User
{
    public long Id { get; set; }
    public string Email { get; set; }
    public string Country { get; set; }
    public DateTime? LastLogin { get; set; }
    public string OtherData { get; set; }
}
```

and a Simple select query:
```sql
SELECT 
  "User"."Id", 
  "User"."Email", 
  "User"."LastLogin", 
  "User"."OtherData"
FROM 
  "User" 
WHERE "User"."Id" = 1;
```

**Comment by jonwagner** [comment]
This *should* just work as-is if you have the latest Ngpsql in your project. If not, I can take care of it.

I'd also like to add support for automatically serializing objects into the json field, much like how Insight auto-serializes objects to XML fields on SQLServer. That might just take me a little time to get around to.

**Comment by jonwagner** [comment]
Alright, this isn't "just working," but I'll fix it...

**Comment by jonwagner** [comment]
The next build (probably v5.2.4) will have this support in it.

It works pretty well, and there's only one gotcha. I updated the documentation on the wiki:

https://github.com/jonwagner/Insight.Database/wiki/PostgreSQL-Provider

I will likely do an official build early this week.

**Comment by AjmalVh** [comment]
Hi @jonwagner 

Thank you for your support :+1:

**Comment by jonwagner** [comment]
This is live in v5.2.4
