### ISSUE TITLE
ID from Insert/Upsert is not merged back into object

### ISSUE THREAD

**Issue by jeroenbu** [jonwagner/Insight.Database#196]
Hi,
I use the auto-interface implementation of Insight with the AUTOPROCs to insert an object into the database. I've noticed that the generated ID of the insert is not merged back into the object that's being insert.

Thx,

Jeroen

This is the setup that I use:

AUTOPROC generated insert:
```
create procedure [InsertGebruiker]
    (
     @Naam varchar(100)
    ,@IsGroep bit
    ,@Code varchar(100) = null
    ,@SpecialistId int = null
    )
as
declare @T table ([Id] int)

insert  into [dbo].[Gebruikers]
        (
         [Naam]
        ,[IsGroep]
        ,[Code]
        ,[SpecialistId]
        )
output  Inserted.[Id]
        into @T
values
        (
         @Naam
        ,@IsGroep
        ,@Code
        ,@SpecialistId
        )
select
    *
from
    @T
```

Interface:
```
    public interface IGebruiker
    {
        int InsertGebruiker(Gebruiker gebruiker);
    }
```

Usage:
```
    public class Gebruiker
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Naam { get; set; }
        public bool IsGroep { get; set; }
        private int? SpecialistId { get; set; }

        public static void Insert(Gebruiker gebruiker)
        {
//Id = 0 here
            Connection.As<IGebruiker>().InsertGebruiker(gebruiker);
//Id = 0 here? Would expect the ID of the inserted record??
        }
    }
```

**Comment by jonwagner** [comment]
(Unfortunately, I don't have a test case that combines the AUTOPROC with an interface. Looks like I should.)

I have test cases that do this:

    INSERT INTO Table (...) OUTPUT Inserted.Id

My guess is that in the autoproc, it's returning two recordsets:

   INSERT -> empty recordset
   SELECT * FROM tmp -> has the ids

It might be solved by adding SET NOCOUNT ON at the top of the proc.

Hopefully, that helps you until I have time to dive into the details.

**Comment by jeroenbu** [comment]
I'm not sure that's the case, although it sounds plausible. However, when I execute this in Management Studio:
```
exec InsertGebruiker @Naam=N'Harry Noname',@IsGroep=0,@Code=N'MYDOMAIN\harry',@SpecialistId=NULL
```
the result is just the ID of the inserted record, and the message "Command(s) completed succesfully". No indication of an extra recordset.

**Comment by jonwagner** [comment]
Well, it works with Beer :)

		public interface IInsertBeers
		{
			void InsertBeer(Beer b);
		}

		[Test]
		public void AutoprocInsertBeerShouldReflectID()
		{
			var beer = new Beer() { Name = "Stoutly", Style = "Stout" };
			Assert.AreEqual(0, beer.ID);
			Connection().As<IInsertBeers>().InsertBeer(beer);
			Assert.AreNotEqual(0, beer.ID);
		}

So let me see if I can find the difference.

**Comment by jonwagner** [comment]
Aha.

    void InsertBeer(Beer b); // works
    int InsertBeer(Beer b); // doesn't

And now to find out why...

**Comment by jonwagner** [comment]
ah, if you make the return type int, Insight assumes that you want the recordset to be returned as a scalar. In fact, you'll see that the method actually returns the ID.

It would probably be the same with multiples:

    void InsertBeers(IEnumerable<Beer> list); // merges outputs
    IEnumerable<int> InsertBeers(IEnumerable<Beer> list); // doesn't merge outputs, returns ids

So the options are:

1. Leave it alone. (perhaps leaving a warning in the wiki)
2. Don't let people create an interface method called InsertXXX with a non-null return value. (would be a breaking change in 6.0)
3. Attempt to merge the recordset and also return the value. (too much ick for my tastes.)

**Comment by jonwagner** [comment]
The document alludes to this behavior, but I think at least a warning is in order:

* void, method name starts with "Insert/Upsert", first param is IEnumerable => InsertList
* void, method name starts with "Insert/Upsert", first param is updatable -> Insert

**Comment by jonwagner** [comment]
I've unanimously voted to leave this alone for now (with a wiki update).

Let me know if you have any more issues.

**Comment by jeroenbu** [comment]
I concur with the unanimous vote, making it even more unanimous. I've changed the methods to return void instead of int/IEnumerable<int>.

Thx for looking into this!
