### ISSUE TITLE
Parameter mapping doesn't map properties from base interfaces

### ISSUE THREAD

**Issue by Hinidu** [jonwagner/Insight.Database#197]
Hello!
I found that if I use something like:
```csharp
interface A
{
    int Foo { get; set; }
}
interface B : A
{
    int Bar { get; set; }
}
interface DB
{
    [Sql("INSERT INTO b VALUES (:foo, :bar)"]
    void InsertB(B b);
}
```
The ```:foo``` field is not mapped. But if I move ```Foo``` to ```B``` then ```InsertB``` works correctly.
The reason is that [GetMembersForType](https://github.com/jonwagner/Insight.Database/blob/89c4ac243b24768e4f3f3edefa53e17279c372b2/Insight.Database/CodeGenerator/ClassPropInfo.cs#L184) uses ```Type.GetProperties``` but that method unfortunately doesn't return properties from base interfaces. It can be fixed by manually iterating recursively over all base interfaces and merge their properties.
Thank you in advance!

**Comment by jonwagner** [comment]
What is the class of the object that you're passing into the InsertB method? As it turns out, when mapping parameters, Insight uses the type of the actual object, not the type on the signature.

So, this should work:

    public class AB : B
    {
        public int Foo { get; set; }
        public int Bar { get; set; }
    }

    var ab = new AB() { ... }
    c.InsertB (ab); // insight will actually map the fields on AB, and foo/bar are both on that class.

I got it to fail with this case:

			public class AB : B
			{
				int A.Foo { get; set; }
				int B.Bar { get; set; }

				public AB(int foo, int bar)
				{
					((A)this).Foo = foo;
					((B)this).Bar = bar;
				}
			}

    var ab = new AB() { ... }
    c.InsertB (ab); // there are no properties directly on AB to map.


I'm not sure I want to go through the trouble of trying to map non-public interface members. Certainly not without seeing your use case first.

**Comment by Hinidu** [comment]
Sorry, I just tried to do it again and it works well now. It seems like there was an error somewhere else. I've should try to reproduce this bug in a small project. I'm really sorry for the inconvenience.

**Comment by Hinidu** [comment]
Hello! I've encountered this problem again... But this time I reproduced this behavior in one-file project:
```c#
using System;
using Insight.Database;
using Npgsql;

namespace Insight
{
    public interface IRepository
    {
        [Sql("SELECT a + b + c FROM (SELECT :a AS a, :b AS b, :c AS c) AS t")]
        int Sum(int c, IBar bar);
    }

    public interface IFoo
    {
        int A { get; set; }
    }

    public interface IBar : IFoo
    {
        int B { get; set; }
    }

    public class Bar : IBar
    {
        public int A { get; set; }
        public int B { get; set; }
    }

    class Program
    {
        static void Main()
        {
            const string connectionString = "MY_CONNECTION_STRING";
            var connection = new NpgsqlConnection(connectionString).As<IRepository>();
            Console.WriteLine(connection.Sum(10, new Bar { A = 42, B = 13 }));
        }
    }
}
```
Insight generates query ```SELECT a + b + c FROM (SELECT :a AS a, 13 AS b, 10 AS c) AS t``` (it doesn't substitute ```:a```).
I am able to fix this problem by removing ```int c``` argument or by moving ```int A { get; set; }``` inside ```IBar```.
Though I didn't dig in Insight codebase to try to find the cause of that behavior.

**Comment by Hinidu** [comment]
Fixed versions of the code above: https://gist.github.com/Hinidu/d0e60d4e1638906dde49

**Comment by jonwagner** [comment]
Insight performs parameter bindings based on the declared type of the parameter.

    int Sum(int c, IBar bar);

In this case, you've bound the parameter to IBar, and A is not a member of IBar, so the parameter is not bound.

If you declare the parameter as `Bar`, the code works as expected.

**Comment by Hinidu** [comment]
Oh, it was so simple... How could I don't think about it...
The only strange thing then is why itchange its behavior if I remove `int c ` argument. fix1 in https://gist.github.com/Hinidu/d0e60d4e1638906dde49

**Comment by Hinidu** [comment]
Sorry, I was just waking up when wrote previous comment...
> In this case, you've bound the parameter to IBar, and A is not a member of IBar, so the parameter is not bound.

But `IBar` implements `IFoo` so in my opinion `A` is a member of `IBar`. Did you notice that inheritance? Or do you think that it doesn't matter?

And now you're saying that:
> Insight performs parameter bindings based on the declared type of the parameter.

But in the previous discussion you've said opposite:
> As it turns out, when mapping parameters, Insight uses the type of the actual object, not the type on the signature.

Are you sure that it uses declared type?
