### ISSUE TITLE
Support for great-grandchildren

### ISSUE THREAD

**Issue by bhuvakunal** [jonwagner/Insight.Database#198]
I can query for an object with children and its grandchildren:

```javascript
var someObject = connection.Query("SomeStoredProc", new {ParentId = id},
Query.Returns(Some<Parent>.Records)
                .ThenChildren(Some<Child>.Records)
                .ThenChildren(Some<Grandchild>.Records,
                        parents: parent=> parent.Children,
                        into: (child, grandchildren) => child.Grandchildren = grandchildren));
```

I have a set of tables
Parent -> Child -> Grandchild -> Great-Grandchild

I tried using RecordId, ParentId, ChildRecords attribute to no avail. Also, all my classes are decorated with [BindChildren(BindChildrenFor.All)].

Is there a way I have the populate the Great-Grandchildren? Thanks!

**Comment by bhuvakunal** [comment]
This is not an issue. I posted this on the wrong forum.
I apologize. I have posted this question on Stack Exchange: http://stackoverflow.com/questions/29024916/support-for-great-grandchildren-insight-database

**Comment by jonwagner** [comment]
The pattern is similar to grandchildren. For the parents: selector, you just need to use a SelectMany to get the full list of grandchildren.

(At least, that's how it's supposed to work...)

var someObject = connection.Query("SomeStoredProc", new {ParentId = id},
Query.Returns(Some<Parent>.Records)
                .ThenChildren(Some<Child>.Records)
                .ThenChildren(Some<Grandchild>.Records,
                        parents: parent=> parent.Children,
                        into: (child, grandchildren) => child.Grandchildren = grandchildren)
                .ThenChildren(Some<GreatGrandchild>.Records,
                        parents: parent=> parent.Children.SelectMany(c => c.Grandchildren)),
                        into: (grandchild, greatgrantchildren) => grandchild.greatgrantchildren= greatgrantchildren));
);

**Comment by jonwagner** [comment]
BTW - I don't mind if you ask questions on github, but it's nice to ask them on stackoverflow so more people learn about Insight.Database.

Thanks for your support!
