### ISSUE TITLE
ColumnName is overridden when using OneToOne reader with types that derive from the same base type.

### ISSUE THREAD

**Issue by joeshifflett** [jonwagner/Insight.Database#199]
Given the classes:

    public abstract class BaseRecord
    {
        public abstract int? Id { get; set; }
        ...
    }

    public class ChildRecord : BaseRecord
    {
        [Column("ChildRecordID")]
        public override int? Id { get; set; }

        internal GrandChildRecord GrandChild { get; set; }
        ...
    }

    public class GrandChildRecord : BaseRecord
    {
        [Column("GrandChildRecordId")]
        public override int? Id { get; set; }
        ...
    }

When I execute this:

    var result = conn.Single<ChildRecord, GrandChildRecord>("getChildRecords", new { ID = -1135522 });

The Id of the result is null.  I believe the root cause is because of this line in GetMembersForType in ClassPropInfo:

    // if we override the column name at this level, then apply it to the mapping
    // i'm not happy that we're modifying columnmame, but we know that the object was created just for this loop.
    match.ColumnName = p.ColumnName;

I solved this by cloning the base members instead.  So I changed this:

    // if there is a base type, get those members first
    // derived classes won't have access to the private members of the base class
    if (type.BaseType != null)
    members.AddRange(GetMembersForType(type.BaseType));

To this:

    // if there is a base type, get those members first
    // derived classes won't have access to the private members of the base class
    if (type.BaseType != null)
    members.AddRange(GetMembersForType(type.BaseType).Select(x => new ClassPropInfo(x.MemberInfo)));

This does work but let me know if you have a better solution.  Thanks.

**Comment by jonwagner** [comment]
Cool. I'll dig into it.

**Comment by jonwagner** [comment]
At least I knew I was being bad when I wrote that bit of code. :)

Your fix was pretty close. I just made it so I'm not likely to break it again later.

Fix will be in v5.2.5 or later.

**Comment by joeshifflett** [comment]
Cool. Yeah I like that change better.  Thanks!
