### ISSUE TITLE
"Composite Keys" documentation

### ISSUE THREAD

**Issue by pafnow** [jonwagner/Insight.Database#201]
Hi,
I'm getting back to use this awesome module and I'm setting up some composite keys relationship.
I'm not yet fully done with the integration but found out some possible ameliorations on the documentation.

1) https://github.com/jonwagner/Insight.Database/wiki/Specifying-Result-Structures#composite-keys
You write :
```
var results = connection.Query("GetBeerAndPossibleGlasses", Parameters.Empty,
    Query.Returns(Some<Beer>.Records)
        .ThenChildren(
            Some<Glasses>.Records.GroupBy(g => Tuple.Create(g.ID1, g.ID2)),
            id: beer => Tuple.Create(beer.BeerID1, beer.BeerID2),
            into: (beer, glass) => beer.Glasses = glass);
```
but from my test, the Tuple.Create is referring to the child class Glasses in this case so it should be
```
var results = connection.Query("GetBeerAndPossibleGlasses", Parameters.Empty,
    Query.Returns(Some<Beer>.Records)
        .ThenChildren(
            Some<Glasses>.Records.GroupBy(g => Tuple.Create(g.BeerID1, g.BeerID2)),
            id: beer => Tuple.Create(beer.ID1, beer.ID2),
            into: (beer, glass) => beer.Glasses = glass);
```
Am I mistaken?

2) https://github.com/jonwagner/Insight.Database/issues/147#issuecomment-57345769
You explain here how to map with parent ids not in the child class.
I think the documentation mention this in this sentence: 

> If you don't specify a hint or attribute for the child class, Insight will assume that the number and type of key columns match the parent class, but will store them outside the child class when grouping the objects. In this case, the key fields need to be the first columns in the child recordset.

What about giving some examples as you did in your comment for the issue 147?

Anyhow, thanks again for the awesome module and I will post an issue if I can't finalize my integration.
Cheers,

**Comment by jonwagner** [comment]
1) i didn't actually test the code in the docs, so I'm probably wrong. Feel free to update the wiki.
2) 

    class Beer { int id; List<Glass> glasses; }
    class Glass { int size; }

    SELECT * FROM Beer;
    SELECT b.id, g.* FROM Beer JOIN Glass;

    var b = c.Query(sqlabove);

Note that when returning the glasses, beer.id is used to assign the glass to the parent, but there's no parentid field on glass. Insight magically handles this for you.

**Comment by pafnow** [comment]
Hi,
Thanks for your answer, just update the wiki page.
Cheers
