### ISSUE TITLE
Custom mapping breaks Query method

### ISSUE THREAD

**Issue by jfrank14** [jonwagner/Insight.Database#203]
I ran into a situation where a stored proc had a column whose name starts with a number e.g. `4ever` (bad idea, but TSQL allows it). .NET identifier names can't start with a number, so I named the variable `_4ever`. To get this to work with Insight in a general way, I made a column mapper that renamed any column starting with a number by prepending an underscore. In VB, this looks like this:

>Class ColumnMapper
        Implements Mapping.IColumnMapper
            Public Function MapColumn(type As Type, reader As IDataReader, column As Integer) As String Implements Mapping.IColumnMapper.MapColumn
                Dim name = reader.GetName(column)
                Return If(name.IsMatch("^\d"), "_" & name, name)
        End Function
    End Class

But now I get this error from Insight:
>Insight.Database.DBConnectionExtensions.Query.51[DBConnectionExtensions.generated.cs]
Insight.Database.DBConnectionExtensions.Query.497[DBConnectionExtensions.cs]
Insight.Database.DBConnectionExtensions.ExecuteAndAutoClose.1461[DBConnectionExtensions.cs]
Insight.Database.DBConnectionExtensions.<>c__DisplayClass69`1.b__68.501[DBConnectionExtensions.cs]
Insight.Database.Structure.ListReader`1.Read.55[ListReader.cs]
Insight.Database.DBReaderExtensions.d__0`1.MoveNext.75[DbReaderExtensions.cs]
Insight.Database.OneToOne`1.GetRecordReader.197[OneToOne.cs]
Insight.Database.CodeGenerator.DbReaderDeserializer.GetDeserializer.104[DbReaderDeserializer.cs]
Insight.Database.CodeGenerator.DbReaderDeserializer.GetDeserializer.172[DbReaderDeserializer.cs]
Insight.Database.CodeGenerator.DbReaderDeserializer.<>c__DisplayClass5.b__4.174[DbReaderDeserializer.cs]
Insight.Database.CodeGenerator.ClassDeserializerGenerator.CreateDeserializer.51[ClassDeserializerGenerator.cs]
Insight.Database.CodeGenerator.ClassDeserializerGenerator.CreateClassDeserializer.77[ClassDeserializerGenerator.cs]
Insight.Database.CodeGenerator.ClassDeserializerGenerator.CreateClassDeserializerDynamicMethod.109[ClassDeserializerGenerator.cs]
Insight.Database.CodeGenerator.ClassDeserializerGenerator.MapColumns.351[ClassDeserializerGenerator.cs]
Insight.Database.ColumnMapping.MapColumns.82[ColumnMapping.cs]
Insight.Database.ColumnMapping.<>c__DisplayClass4.b__3.83[ColumnMapping.cs]
Insight.Database.ColumnMapping.MapColumn.167[ColumnMapping.cs]
Insight.Database.DbSerializationRule.GetSerializer.210[DbSerializationRule.cs]
Insight.Database.DbSerializationRule.EvaluateRules.220[DbSerializationRule.cs]

I'm about to dig into the source code, but I'm wondering if there's anything in particular I should be looking for that could cause this. The class I'm mapping in this call, by the way, does **NOT** have any columns that start with a number, so the mapping shouldn't even be doing anything.

**Comment by jfrank14** [comment]
**Update**: I found the immediate cause of the error, and how to work around it, but I'm not sure that the Insight behavior is correct or intuitive.

In the error I was getting, the proc had fields with names like `First Name` or `Row #`. A .NET identifier can't have spaces or punctuation, so I mapped these to `Property FirstName As String` or `Property Row As Integer`. By default, Insight does this mapping, and removes spaces and punctuation for you. But my custom mapper didn't do this, and so the field remained `First Name`, with the space, and then Insight couldn't match this up with my `FirstName` (no spaces) property, and threw this Exception.

The fix was for my custom mapping to remove spaces and punctuation as well, but it seems to me that Insight should probably do this by default, even after custom mapping, because there's no scenario where a .NET identifier could have those characters in the name. Failing that, it'd be nice if there were a built in method like `ToIdentifier` that does the same thing Insight does internally, so that it could be called from the map function, so that implementers don't have to reinvent the mapping rule that Insight already uses.

**Comment by jonwagner** [comment]
Yeah, it would probably be good to expose that functionality.

In the meantime, you probably could just add a regex replace mapping handler. I think that framework is set up to chain the rules properly.

**Comment by jfrank14** [comment]
How does chaining work? It looks like the method returns the name of the column, or else null if the mapping doesn't apply to that column. But I don't see how you can return a mapped name but then have the framework apply its own rules in addition.

**Comment by jonwagner** [comment]
Try something like this:

    ColumnMapping.Tables.ReplaceRegex("^(?<digit>\d)", "_${digit}");

**Comment by jfrank14** [comment]
This worked perfectly, and is much cleaner than the column mapping solution. Thanks!
