### ISSUE TITLE
3 or more levels do not automap

### ISSUE THREAD

**Issue by zjem** [jonwagner/Insight.Database#204]
I am currently using automap interface method (https://github.com/jonwagner/Insight.Database/wiki/Auto-Interface-Implementation#result-structures) where a recordset attribute is specified above the interface method to retrieve data.  This data then maps to defined class hierarchy.

When I try to map 3 or more levels, the mapping fails.  I note that there is an extension method (https://github.com/jonwagner/Insight.Database/wiki/Specifying-Result-Structures#three-or-more-levels).  Is there an equivalent automap interface method?

**Comment by elaxby** [comment]
Sry to bump this old Question but can someone help with this?

**Comment by jonwagner** [comment]
I haven't implemented arbitrary mapping functions using attributes yet.

It might be possible to do it in ChildMapperHelper.GetListSetter, but it would be a non-trivial task.
