### ISSUE TITLE
Switch to official Oracle Managed Provider package

### ISSUE THREAD

**Issue by DamianReeves** [jonwagner/Insight.Database#205]
Oracle is now providing an official package for its managed driver on NuGet. That should be the one that is used. Oracle.ManagedDataAccess

**Comment by jonwagner** [comment]
This is fixed in v5.2.6

**Comment by DamianReeves** [comment]
This doesn't seem to be fixed as nuget.org reports odp.net.managed as the dependency and now that nuget has unlisted this odp.net.managed as per Oracle's request this really needs to be corrected.
