### ISSUE TITLE
Support for informix

### ISSUE THREAD

**Issue by ngcammayo** [jonwagner/Insight.Database#206]
Hi does it support informix database? If not how would it be implemented on your base code? 

Thanks for this wonderful orm.

**Comment by juancgarciaco** [comment]
Hi, i did it with db2 driver and drda protocol on Informix database

-----Mensaje original-----
De: "Norberto Cammayo" <notifications@github.com>
Enviado el: ‎27/‎04/‎2015 4:55 p. m.
Para: "jonwagner/Insight.Database" <Insight.Database@noreply.github.com>
Asunto: [Insight.Database] Support for informix (#206)

Hi does it support informix database? If not how would it be implemented on your base code? 
Thanks for this wonderful orm.

**Comment by juancgarciaco** [comment]
Did it work???

**Comment by jonwagner** [comment]
I haven't tried Informix, but it's possible that you can use the DB2 driver or ODBC or OLEDB. You wouldn't have any advanced features with ODBC, but you'd be up and running.

I won't have the time to tackle a new provider, but you can look at the code for the Insight.Database.Providers.DB2 package. The code would likely be very similar.
