### ISSUE TITLE
BOOL type not handled correctly with PostGres

### ISSUE THREAD

**Issue by jbright** [jonwagner/Insight.Database#207]
In PostGres, create a table with zero records that includes a column of type BOOL. Then write a query like:

    Database
    .Connection()
    .QuerySql<SomeObject>(
         "SELECT * FROM Foo WHERE is_true = @isTrue LIMIT 1", new
                {
                    @isNew = true,
                })

You will get an exception: 

Unhandled Exception: Npgsql.NpgsqlException: ERROR: 42804: column "is_true" is of type boolean but expression is of type integer

PG expects values of TRUE and FALSE. I.e.

    SELECT * FROM Foo WHERE is_true = TRUE

and 

    SELECT * FROM Foo WHERE is_true = FALSE

.

**Comment by Hinidu** [comment]
Hi @jbright! You have ```@isTrue``` in command but ```@isNew``` in the object. Is it just a typo? Is there the same problem even with the matching names?

**Comment by jbright** [comment]
@Hinidu I think that was just a transcription issue from when I converted my actual code to a sample code. I can double check though...

**Comment by jbright** [comment]
Yes. this still appears to be an issue. It might have something to do with PostGres using TRUE and FALSE instead of 1 and 0.

**Comment by jonwagner** [comment]
Added this test case, which works in 5.2.6

		#region Issue 207
		[Test]
		public void TestIssue207()
		{
			using (var connection = _connectionStringBuilder.Connection().OpenWithTransaction())
			{
				connection.ExecuteSql("CREATE TABLE foo (id int, isnew bool)");
				connection.ExecuteSql("INSERT INTO foo VALUES (1, true)");
				connection.ExecuteSql("SELECT * FROM foo WHERE isnew = @isnew", new { isnew = true });
			}
		}
		#endregion
