### ISSUE TITLE
Executing Stored Procedure.

### ISSUE THREAD

**Issue by scharada** [jonwagner/Insight.Database#208]
hi, why is the sample data program not working when executing this statement: (using it on sqlexpress)
Beer beer = new Beer() { Name = "IPA" };

			// map a beer the stored procedure parameters
			Database.Connection().Insert("InsertBeer", beer);

the SP needs 2 parameters but the call appends only the first. 
i'd like to beilieve the sample program and database are out of date . is that the case ?

**Comment by jonwagner** [comment]
The sample code seems to work with the latest db that's built by the test cases.
Most likely it's just out of date, since I do most of my testing with the test program and not the sample code.
