### ISSUE TITLE
Abstract Repository Issue with OpenWithTransactionAsAsync

### ISSUE THREAD

**Issue by wafaha11** [jonwagner/Insight.Database#209]
Hi Jon,

I've been facing problems opening a connection with transaction when my repository is an abstract class implementing IDbConnection and IDbTransaction. I have the latest version of Insight.database and its dependencies. (Version 5.2.2)

My repository looks like this
```c#
public abstract class EntityRepository : IDbConnection, IDbTransaction 
{
        #region Private Fields
        protected internal String ConnectionString { get; set; }
        #endregion

        #region Properties
        public IDbConnection DB
        {
            get
            {
                return this.GetConnection();
            }
        }
        #endregion

        public abstract IDbConnection GetConnection();
        public virtual Task UpdateAsync(T entity, bool triggerOnUpdate = true)
        {
           return this.UpdateAsync(entity, this.GetProcedureName(CommonProcedures.Update),
triggerOnUpdate);
        }
}
```
I am creating an instance of this repository like this
```c#
Database db = new SqlDatabase(connectionString);
var connection = db.CreateConnection();               
var repository = await connection.OpenWithTransactionAsAsync<EntityRepository>();
```
However, I am getting the following error: innerConnection must be derived from DbConnection.
So should my abstract class inherit/implement DbConnection instead? Please get back to me as soon as you can to resolve this issue as I have been trying to tackle it for the past week. Plus I have looked for examples using abstract class online but couldn’t find any.

**Comment by jonwagner** [comment]
It's probably safest to derive from DbConnectionWrapper. All of the internal wiring is there for you. I plan on keeping DbConnectionWrapper as a part of the API, so it's safe to use.
