### ISSUE TITLE
DBNull to default(t) silent successful conversion for non-nullable types

### ISSUE THREAD

**Issue by jamezor** [jonwagner/Insight.Database#211]
We have been bitten by a unexpectedly successful conversion from DBNull to default(t) for non-nullable types.

e.g. `connection.ExecuteScalarSql<int>("select unexpectedly_null_value from a_table")` will return 0; whereas we expected this to explode and highlight that the query was incorrect.

The fix is obviously to correct our query to filter out null results (or whatever); but it would be great if this type of silent conversion did not occur.

**Comment by jonwagner** [comment]
Hm...I can't remember why it's set that way, but I feel like I already fixed that.

Are you on the latest build?

**Comment by jamezor** [comment]
I've written two tests showing the issue if you have a moment to check them out.

**Comment by jonwagner** [comment]
I've made the change in the 6.0 branch, because it will change behavior for existing users.
It's more consistent this way, but I don't want to break anyone unknowingly.
