### ISSUE TITLE
Expression<Func<T, bool>> to Find parameter?

### ISSUE THREAD

**Issue by pbolduc** [jonwagner/Insight.Database#212]
Hi Jon,  

I was wondering if you know of any help/extension methods we can use to convert simple Expression&lt;Func&lt;T, bool>> to the correct anonymous type for Find Auto Proc generated stored procedures?

    var parameters = FindHelper.ToFindParameter((beer) => beer.Flavor == "IPA" && beer.Cost <= 10);
    // parameters = new { Flavor = "IPA", FlavorOperator = "=", Cost = 10, CostOperator = "<=" };
    var beers = beerRepository.FindBeer(parameters);

I have found bugs (my bugs) using the Find methods because my columns and associate properties were renamed, but we missed the usages in the anonymous parameter.

It is obvious a given property could only be used once in the expression.  For more complex filter criteria, the user would have to create custom stored proc. I started to write a helper method that did this, but thought I would ask if you have something like this or heard of someone creating something like this.

**Comment by jonwagner** [comment]
Ah, yes. That's definitely dynamic binding there and it could bite you.

If your objects are simple you can do:

    class Beer {}
    class FindBeer : Beer { /* add FlavorOperator */ }

then

    repo.FindBeer(new FindBeer { /* blah */ }

there's nothing special about the object passed to find. It just binds it to the parameters of the proc.

**Comment by pbolduc** [comment]
Yes, that would also work.  Thanks for the feedback.
