### ISSUE TITLE
Linux, Mono and postgreSQL problem

### ISSUE THREAD

**Issue by randall84** [jonwagner/Insight.Database#218]
Hello,
this is Andrea from Italy.

I'm not able to connect(linux+mono) to postgresql with your library.
I've tried with npgSql and if functs.
thanks in advance

First example with npgSql(if functs)

               using (var conn = new NpgsqlConnection("Host=127.0.0.1;Username=postgres;Password=me;Database=tst_aspnet"))
				{
					conn.Open();
					using (var cmd = new NpgsqlCommand())
					{
						cmd.Connection = conn;
						// Retrieve all rows
						cmd.CommandText = "SELECT * FROM articoli";
						using (var reader = cmd.ExecuteReader())
						{
							while (reader.Read())
							{
								_lbl_tst.Text += reader["testo"].ToString();
							}
						}
					}
				}

Second example with insight db(doesn't functs :-( )

	            PostgreSQLInsightDbProvider.RegisterProvider();
				SqlConnection wSqlConnection = new SqlConnection ("server=127.0.0.1,5432;User Id=postgres;Password=me;Database=tst_aspnet");
				wSqlConnection.ExecuteSql("SELECT * FROM articoli");

**Comment by randall84** [comment]
the same problem in windows...

**Comment by randall84** [comment]
solved with this code:

      PostgreSQLInsightDbProvider.RegisterProvider( );
         
         NpgsqlConnectionStringBuilder _connectionStringBuilder = new NpgsqlConnectionStringBuilder( );
         _connectionStringBuilder.ConnectionString = "connection";
         DbConnection _connection = _connectionStringBuilder.Open( );

**Comment by jonwagner** [comment]
What error are you receiving?

**Comment by janus007** [comment]
Hi randall

You should probably connect to PostgreSql like this:

I believe you are mixing SqlConnection with PostgreSql in your first example, so...
```c#
var connString = @"Server=vixens; port=5432;Database=glogg_dev;User Id=glogg;Password=glogg;";
    
using (var conn = new NpgsqlConnection(connString))
{
    var d = conn.QuerySql("SELECT * FROM insightTest");
}
```

**Comment by janus007** [comment]
Hi Jon

I tried my own solution, but without any luck.

I receive an error:
d
error CS7069: Reference to type 'FastExpando' claims it is defined in 'Insight.Database', but it could not be found.

I'm using DNX 4.5.1

The funny thing is if I execute along with the above: FastExpando x = app.Expand(); it finds FastExpando, but when var d still gives me the same error.

My dependencies:

 "dependencies": {
    "Microsoft.AspNet.Server.IIS": "1.0.0-beta4",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-beta4",
    "Hangfire": "1.5.0-beta2",
    "Microsoft.AspNet.Owin": "1.0.0-beta4",
    "Hangfire.PostgreSql": "1.3.4",
    "Insight.Database": "5.2.6",
    "Insight.Database.Providers.PostgreSQL": "5.2.6",
    "System.Data.SqlClient": "4.0.0-beta-22816"

  }

**Comment by jonwagner** [comment]
This is a compile-time error?

Here's a link to someone having a similar issue:

http://stackoverflow.com/questions/30468387/visual-studio-cannot-find-reference

Are there multiple Insight.Database dlls in the path somehow?

**Comment by janus007** [comment]
The solution compiles just fine, the problem arise when I debug and try to access "var d" in immediate window.

If you have Procmon, I've a dump of Insight.Database file access here: https://www.sevenweirdpeople.io/owncloud/index.php/s/AhxVqDq2yrFOv2T

It seems that only one Insight.Database.dll is found. I tried to IL it, and of course it has FastExpando inside it. 
Something fishy in the air :)

**Comment by jonwagner** [comment]
Aha. Insight creates some dynamic assemblies with the same name, so it's likely that there's a conflict with those. V6.0 may already have a fix for this but its unreleased.

**Comment by janus007** [comment]
Okay, I see.
Well, at the moment I only use INSERTS so I will just wait.

btw. keep up the good work, sometimes I wonder why I even bothered with World domination ORM's :)

**Comment by fomenta** [comment]
Fixed bug on Visual Studio 2015.
Go to Tools menu, Options, Debugging, General: Check: "Use the legacy C# and VB expression evaluators"

**Comment by kevinsea** [comment]
Closing since this is duplicated by #224 (which has a pending pull request :) )
