### ISSUE TITLE
How to receive the result of QuerySql in a view web page?

### ISSUE THREAD

**Issue by cy598** [jonwagner/Insight.Database#220]
I do love this tool. And i do have written my first insightdb controller. It accessed my database favorably, the only question is how to receive the result of QuerySql in a view web page.

I used the follow codes in my controller:

<pre>var mydb = new MySqlConnectionStringBuilder("....connectionstring...");
// run a query right off the connection (this performs an auto-open/close)
var provinces = mydb.Connection().QuerySql("SELECT * From provinces");
return View(provinces.ToList());</pre>
        
And used the follow codes in my view (index.cshtml)

<pre>@model IEnumerable<MySQL_MVC_Template1.Models.provinces>
@{   WebGrid grid = new WebGrid(Model);}
\<h2\>provinces List\<h2\>
\<div id="grid"\> 
  @grid.GetHtml()
\</div\></pre>

But the system showed me : the import is “System.Collections.Generic.List\`1[Insight.Database.FastExpando]”，but the dictionary needs “System.Collections.Generic.IEnumerable\`1[MySQL_MVC_Template1.Models.yunclear_provinces]”。

So, how can i show the query result in the view? thank you.

**Comment by jonwagner** [comment]
QuerySql will return a list of dynamic objects.
If you want it to return your model, try:

    QuerySql<your specific type>(...)

**Comment by cy598** [comment]
Thank you so much!
Could you kindly give me some codes, show me how could i receive the dynamic objects list in a view page? And how could i traversal this list using "foreach" to output the attribute values for each object.

Thanks again.

**Comment by jonwagner** [comment]
The wiki has some great examples. That's about all I can provide at this time.
