### ISSUE TITLE
Learn Insight

### ISSUE THREAD

**Issue by WerterAllan** [jonwagner/Insight.Database#221]
How can I learn deeply about the techniques used to build this micro orm? could you give me some sites and book?

This tool is incredible, congratulations.

**Comment by cy598** [comment]
Me too，i need an example on how to receive the result of QuerySql in a view and traversal the objects list in the result.
Of course I have  flipped through the wiki , but it seemed there were some codes of howto operate the database only.

**Comment by WerterAllan** [comment]
My doubt is about the engineering of this project. I want ententer each code file. I downloaded the source code and I'm debbugando each code line to understand. I use C # to 3 years and would like to delve into the development of ORM. I hope one day to contribute to this project.

**Comment by cy598** [comment]
I just solved the problem in using insight.database in the view file. I do love this tool and wish you all  well!
