### ISSUE TITLE
Can't  find  DbConnectionStringBuilderExtensions.cs

### ISSUE THREAD

**Issue by cy598** [jonwagner/Insight.Database#225]
Hi all...
When I used the follow codes in controller:
<pre> 
var country = new MySQL_MVC_Template1.Models.countries();
country.name_countries = formCollection["name_countries"];
country.continent_countries = formCollection["continent_countries"];

mydb.Connection().ExecuteSql("INSERT INTO countries SELECT * FROM @Country", new { Country = country });</pre>

and follow codes in model
<pre> 
public partial class countries
{
   public long id_countries { get; set; }
   public string name_countries { get; set; }
   public string continent_countries { get; set; }
}
</pre>
The system showed me: "Can't  find  DbConnectionStringBuilderExtensions.cs"
Seems the package does no include such a file. I'm using VS2013 .net 4.5 and mysql 5.5.35

**Comment by cy598** [comment]
Of cours i have tried this：

<pre>
var country = new MySQL_MVC_Template1.Models.countries();
country.name_countries = formCollection["name_countries"];
country.continent_countries = formCollection["continent_countries"];
List<countries> Countries = new List<countries>();
Countries.Add(country);
mydb.Connection().ExecuteSql("INSERT INTO countries SELECT * FROM @Country", new { Country = Countries });
</pre>

the same.

**Comment by kevinsea** [comment]
Hi,

The "Can't find DbConnectionStringBuilderExtensions.cs" sounds like what you would see when the debugger is trying to show you the line with the exception but you don't have the source.  You can download the source or cancel out of the dialog to get to the actual exception.

It would help to post the exact exception message you are getting.

Also, I don't see the code that sets up your connection, how is the connection created?

**Comment by cy598** [comment]
Thank you!
I used follow codes in the controller:

<pre>
	public class CountryController : Controller
    {
		private MySqlConnectionStringBuilder mydb = new MySqlConnectionStringBuilder("server=127.0.0.1;user id=XXX;password=XXX; persistsecurityinfo=True;port=3306;database=Test;allowuservariables=True");

		public ActionResult AddCountry(FormCollection formCollection)
		{
			var country = new MySQL_MVC_Template1.Models.countries();
			country.name_countries = formCollection["name_countries"];
			country.continent_countries = formCollection["continent_countries"];
			List Countries = new List();
			Countries.Add(country);
			mydb.Connection().ExecuteSql("INSERT INTO countries SELECT * FROM @Country", new { Country = Countries });
			return RedirectToAction("Index", "Country");   
		}
	}	
</pre>

**Comment by cy598** [comment]
in Insight.Database.Providers.InsightDbProvider.SetupTableValuedParameter(IDbCommand command, IDataParameter parameter, IEnumerable list, Type listType)  c:\projects.net\Insight\Insight.Database\Insight.Database\Providers\InsightDbProvider.cs:line 288
   in  Insight.Database.CodeGenerator.DbParameterGenerator.ListParameterHelper.ConvertListParameterByClass(IDataParameter parameter, IEnumerable list, IDbCommand command, Type listType) in c:\projects.net\Insight\Insight.Database\Insight.Database\CodeGenerator\DbParameterGenerator.cs:line 729
   in Insight.Database.CodeGenerator.DbParameterGenerator.ListParameterHelper.ConvertListParameter(IDataParameter parameter, Object value, IDbCommand command) position c:\projects.net\Insight\Insight.Database\Insight.Database\CodeGenerator\DbParameterGenerator.cs:line 654
   in CreateInputParameters-15fdbbea-abcd-4819-b5ca-7dc6fb2d8f9f(IDbCommand , Object )
   in Insight.Database.DBCommandExtensions.AddParameters(IDbCommand cmd, Object parameters) position c:\projects.net\Insight\Insight.Database\Insight.Database\Extensions\DBCommandExtensions.cs:line 33
   in Insight.Database.DBConnectionExtensions.CreateCommand(IDbConnection connection, String sql, Object parameters, CommandType commandType, Nullable`1 commandTimeout, IDbTransaction transaction) position. c:\projects.net\Insight\Insight.Database\Insight.Database\Extensions\DBConnectionExtensions.cs:line 276
   在 Insight.Database.DBConnectionExtensions.<>c__DisplayClass61.<Execute>b__5f(IDbCommand _, IDataReader __) position c:\projects.net\Insight\Insight.Database\Insight.Database\Extensions\DBConnectionExtensions.cs:line 328
   in Insight.Database.DBConnectionExtensions.ExecuteAndAutoClose[T](IDbConnection connection, Func`2 getCommand, Func`3 translate, CommandBehavior commandBehavior) positon c:\projects.net\Insight\Insight.Database\Insight.Database\Extensions\DBConnectionExtensions.cs:line 1461
   在 Insight.Database.DBConnectionExtensions.ExecuteAndAutoClose[T](IDbConnection connection, Func`2 getCommand, Func`3 translate, Boolean closeConnection) positon c:\projects.net\Insight\Insight.Database\Insight.Database\Extensions\DBConnectionExtensions.cs:line 1429
   在 Insight.Database.DBConnectionExtensions.Execute(IDbConnection connection, String sql, Object parameters, CommandType commandType, Boolean closeConnection, Nullable`1 commandTimeout, IDbTransaction transaction, Object outputParameters) positon c:\projects.net\Insight\Insight.Database\Insight.Database\Extensions\DBConnectionExtensions.cs:line 324
   in Insight.Database.DBConnectionExtensions.ExecuteSql(IDbConnection connection, String sql, Object parameters, Boolean closeConnection, Nullable`1 commandTimeout, IDbTransaction transaction, Object outputParameters) positon  c:\projects.net\Insight\Insight.Database\Insight.Database\Extensions\DBConnectionExtensions.cs:line 358
   在 MySQL_MVC_Template1.Controllers.CountryController.AddCountry(FormCollection formCollection) positon c:\Users\Frank\Documents\Visual Studio 2013\Projects\MySQL MVC Template1\MySQL MVC Template1\Controllers\CountryController.cs:line 87
   in lambda_method(Closure , ControllerBase , Object[] )
   in System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   in System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   in System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   in System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass42.<BeginInvokeSynchronousActionMethod>b__41()
   in System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass8`1.<BeginSynchronous>b__7(IAsyncResult _)
   in  System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.End()
   in System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   in System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass37.<>c__DisplayClass39.<BeginInvokeActionMethodWithFilters>b__33()
   in System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass4f.<InvokeActionMethodFilterAsynchronously>b__49()

**Comment by kevinsea** [comment]
Your stored procedure or sql needs to expose all of the column names as parameters.  Check out the wiki for lots of examples.
