### ISSUE TITLE
Error calling Oracle stored procedure, unable to derive parameters

### ISSUE THREAD

**Issue by TurquoiseMage** [jonwagner/Insight.Database#226]
Greetings,
I am unable to call an Oracle stored procedure as I keep getting the following error:
"Cannot derive parameters for the stored procedure [procedure name]. Have you loaded the provider that suppoerts OracleCommand?".  ... and yes, the spelling mistake is in the error message :)
I am using the Oracle provided managed driver.
The procedure name and the parameter names I am passing in are all valid and correct.
What could be causing this issue?
Thanks very much for a great product.
Best regards,
Robert

**Comment by kevinsea** [comment]
Have you called register provider per wiki page /Installing-Insight?  Are you registering the managed or regular provider?

The other thing to look at is your permissions.  Perhaps run the same code with a user with dbo rights just to eliminate this possibility.

**Comment by TurquoiseMage** [comment]
Hi Kevin,

I have tried everything. Every time I create a new project and installed
the Insight for Oracle Managed I get the following error/warning:
C:\Program Files
(x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5):
warning MSB3277: Found conflicts between different versions of the same
dependent assembly that could not be resolved.  These reference conflicts
are listed in the build log when log verbosity is set to detailed.

I never get this issue with other projects using just the Oracle Managed
driver, or any other NuGet package.
Only with Insight.

Please can you help me?

Thanks,
Robert

**Comment by kevinsea** [comment]
> Found conflicts between different versions of the same
dependent assembly that could not be resolved.  These reference conflicts
are listed in the build log when log verbosity is set to detailed.

Hi Robert,
Can you look at your build log and provide the messages detailing the dll's and versions that are conflicting?

**Comment by jonwagner** [comment]
It sounds like insight may be binding to a different oracle version than the rest of your project. build logs should help with that.

**Comment by TurquoiseMage** [comment]
Hi Kevin,
I am have been away ill.
I will create the build log today and send it to you as soon as possible.
Thanks,
Robert
