### ISSUE TITLE
Insight.Database.Providers.ManagedOracle

### ISSUE THREAD

**Issue by TurquoiseMage** [jonwagner/Insight.Database#228]
Greetings,
I just pulled the latest packages from NuGet.
When compiling and running the application I get the following exception (buried in an InnerException):
Could not load file or assembly 'Oracle.ManagedDataAccess, Version=4.121.2.0, Culture=neutral, PublicKeyToken=89b483f429c47342' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
The version which is installed together with the Insight package from NuGet is: 4.121.1.0
This is the problem:
Expecting: 4.121.2.0
Version Installed by NuGet: 4.121.1.0
How can I fix this?
Thanks,
Robert Lancaster

**Comment by Pietjan** [comment]
You can redirect the expected version to the deployed version.
In the web.config or the app.config of the application, there should be a bindingRedirect (allready added when installing the Oracle package) node.
The value of newVersion attribute should be the same as the version number of the Oracle.ManagedDataAccess.dll you are deploying.
The value of oldVersion attribute is a range, the value of the expected version should be containted within that range.
