### ISSUE TITLE
How should I handle resultsets with repeated columns of the same name?

### ISSUE THREAD

**Issue by jfrank14** [jonwagner/Insight.Database#229]
I've run into a situation where a proc (whose source I don't control) returns multiple columns of the same name. If a proc returns `Field1`, ..., `FieldN`, I model this with a class that does the same:

    Class MyProc
      Public Property Field1 As Integer
     ...
      Public Property FieldN As Integer
    End Class

But I can't do this with repeated property names, and I can't find an example in the docs about this scenario. To be clear, there aren't multiple resultsets, just one resultset with repeated field names.

What's the right way to handle this?

**Comment by kevinsea** [comment]
In the wiki check out /Record-Readers and /Manual-Transformations.  Also look in Insight.Tests for more working examples.

**Comment by jonwagner** [comment]
You should probably ask if they could kindly fix the proc. :(

Unfortunately, Insight uses column name bindings. I don't think we'll take the time to bind by column index.

I'd say your options are:

1) Write a custom record reader for that recordset. It's not that difficult and it still works with the framework.
2) It might work if you split your data into two classes:

    class Part1 { public int Foo; } class Part2 { public int Foo }
    // then maybe this will automatically split the class on the right boundary
    Tuple<Part1, Part2> MyProc();

Neither is a great solution. Personally, I'd use guilt on the proc owner.
