### ISSUE TITLE
Is there a way to have Insight map a null string to String.Empty instead of null/Nothing

### ISSUE THREAD

**Issue by jfrank14** [jonwagner/Insight.Database#231]
Suppose `proc.somefield` is a varchar, and suppose that there's a corresponding object

    class proc
    {
    ....
    public String somefield;
    }

When you call the proc and map it to this class, if the value of `somefield` is NULL in the database, this is mapped to null in C#.

I'm finding that I would almost always rather this NULL be mapped to `String.Empty`, so that I can use string handling methods on the field and not have to deal with the null vs "" distinction.

Is there a good hook point in Insight to enable this behavior?

**Comment by kevinsea** [comment]
You can set a custom serializer, see https://github.com/jonwagner/Insight.Database/wiki/Object-Serialization.

E.g. to trim trailing spaces you can add an attribute to set a customer serializer

    [Column(SerializationMode = SerializationMode.Custom, Serializer = typeof(TrailingSpaceTrimmer))]
    public string StatusCode { get; set; }

Custom serializer:

    public class TrailingSpaceTrimmer : DbObjectSerializer
    {
		public override bool CanDeserialize(Type sourceType, Type targetType)
		{
			return targetType == typeof(string);
		}
        public override object SerializeObject(Type type, object o)
        {
            return (string)o;
        }
        public override object DeserializeObject(Type type, object o)
        {
            return ((string)o).TrimEnd();
        }
    }

**Comment by IEvangelist** [comment]
@jfrank14 I agree with @kevinsea, I assume that is the route you went and this is no longer an issue?

**Comment by jfrank14** [comment]
I did the simpler and much less elegant thing and just map null to Empty explicitly in code when it's an issue. If I need a more systematic solution, I'll try the custom serializer approach.
