### ISSUE TITLE
Is there a way to use meta data?

### ISSUE THREAD

**Issue by jbarber2015** [jonwagner/Insight.Database#232]
I use Insight.Database to call a stored proc with FastExpando.  However, we have metadata that is a subset of columns.  For example if the proc returns 100 columns and the metadata only has 5 columns I would only want to build the collection of 5 columns based on what metadata I have.  Is there an easy way to do this?

**Comment by kevinsea** [comment]
How about using your metadata to map from the fastexpando to another fastexpando or dynamic object?  I would think you could write a reusable class to to do that.
