### ISSUE TITLE
Stored Procedure Return Value only with QueryResults<Results>

### ISSUE THREAD

**Issue by madrianr** [jonwagner/Insight.Database#233]
Hello,

In my Stored Procedures (INSERT, UPDATE and DELETE) I return different return values depending if the operation runs or there are errors (row is deleted or another user has changed the row)

is the method QueryResults<Results> the only one which I can use to get the return value of my Stored Procedures?

should'nt there also method's like:

db.executeResults<Results>
db.insertResults<Results>

because these Stored Procedures doesn't return rows and "QueryResult" might be not a good name... 
so ExecuteResult would be better or default Execute returns the return value too

regards robert

**Comment by kevinsea** [comment]
Hi,

ExecuteScalar will do this.  https://github.com/jonwagner/Insight.Database/wiki/Executing-SQL-Commands.
