### ISSUE TITLE
Mapping complex object using ThenChildren does not work in oracle

### ISSUE THREAD

**Issue by alinoson** [jonwagner/Insight.Database#235]
Hi,
I have an issue with oracle when  using ThenChildren feature for complex object. The following code crashes with 'ORA-Invalid character' code but works properly  with SQLServer. Does Insight support that feature for oracle? I m using Oracle Data Provider for .NET (ODP.NET).
Thanks for your precisous help.

 var queryResult = connection.QuerySql(
                   string.Format(@"SELECT ID, DESCRIPTION, CUBE_TABLE_NAME, DATABASE_TYPE, CREATED_DATE, MODIFIED_DATE, CREATED_BY, MODIFIED_BY, (CASE WHEN IS_ACTIVE = 0 THEN 'False' else 'True' END) IS_ACTIVE, LAST_BUILD_STRUCTURE_DATE FROM SEI.OLAP_CUBES WHERE ID = 'dd64a289870a4a88942cacfcf16eb2b8';                                       
SELECT CUBE_ID, ID, DESCRIPTION, FIELD_KEY, DATA_TYPE, DATA_PRECISION, DATA_SCALE, IS_AGGREGATE FROM SEI.OLAP_MEASURES WHERE CUBE_ID = 'dd64a289870a4a88942cacfcf16eb2b8';                                        
SELECT S.CUBE_ID, S.* FROM SEI.OLAP_SLICES S WHERE S.CUBE_ID = 'dd64a289870a4a88942cacfcf16eb2b8';      
SELECT OSD.SLICE_ID, OSD.DIMENSION_ID as ID, OD.CUBE_ID, OD.DESCRIPTION, OD.FIELD_KEY, OSD.DIMENSION_ORDER, OD.DATA_TYPE, OD.DATA_PRECISION, OD.DATA_SCALE, (CASE WHEN OD.IS_DESCRIPTION = 0 THEN 'False' else 'True' END) IS_DESCRIPTION                                     
FROM SEI.OLAP_SLICE_DIMENSIONS OSD                                      
INNER JOIN SEI.OLAP_DIMENSIONS OD ON OD.ID = OSD.DIMENSION_ID   
WHERE SLICE_ID IN (  SELECT SLICE_ID FROM SEI.OLAP_CUBES OC                                           
LEFT JOIN SEI.OLAP_SLICES ON OC.ID = OLAP_SLICES.CUBE_ID        
INNER JOIN SEI.OLAP_SLICE_DIMENSIONS ON OLAP_SLICES.ID = OLAP_SLICE_DIMENSIONS.SLICE_ID        
WHERE OC.ID = 'dd64a289870a4a88942cacfcf16eb2b8')                                     
ORDER BY SLICE_ID, DIMENSION_ORDER;                                     
SELECT ID as OLAPDATASOURCE_ID, DATASOURCE_ID as CENTRALPOINT_ID, IS_ACTIVE FROM SEI.OLAP_DATASOURCES WHERE OLAP_DATASOURCES.CUBE_ID = 'dd64a289870a4a88942cacfcf16eb2b8';")
                    , null ,
                    Query.ReturnsSingle(OneToOne<CubeWithAllEntitiesForBuilding>.Records)
                    .ThenChildren(Some<RawMeasureView>.Records)
                    .ThenChildren(Some<SliceWithDimensionsView>.Records)
                    .ThenChildren(Some<RawDimensionView>.Records, parents: o => o.Slices, id: s => s.ID)
                    .ThenChildren(Some<MappingOlapDataSourceAndCentralPointDataSource>.Records)
                    );

**Comment by kevinsea** [comment]
Hi,

Everything i've read indicates this is an issue with your dynamic sql...Oracle seems a bit picky.  I'd try running each statement and see which one is a problem,  Or better yet, can you use a stored proc?

References:
https://coderanch.com/t/306550/JDBC/databases/SQLException-ORA-invalid-character
https://coderanch.com/t/471542/Oracle-OAS/ORA-invalid-character-error-sql
http://www.codeproject.com/Questions/696097/error-ORA-Invalid-character-can-anyone-helpo
