### ISSUE TITLE
BulkCopy Columns mapping not implemented

### ISSUE THREAD

**Issue by tanbchr** [jonwagner/Insight.Database#237]
Is there a reason why this feature is not implemented? The methods are abstract but not implemented.

Here's the code: 

public abstract InsightBulkCopyMappingCollection ColumnMappings { get; }

And in each provider, it like that:

public override InsightBulkCopyMappingCollection ColumnMappings
            {
                                      get { throw new NotImplementedException(); }
            }

**Comment by jonwagner** [comment]
Looks like I forgot to implement bulk copy mappings. :(

I don't think it's hard to implement in PrepareBulkCopy, but we'd have to do that for each provider that supports bulk copy. But if we want to implement bulk copy mappings, I'd probably try to get the mappings out of GetSchemaTable rather than forcing the user to configure them manually. That's probably why I forgot to implement it. I'd like to implement bulk copy mappings. They would be handy.

**Comment by jonwagner** [comment]
These classes are obsolete. There are other methods to perform column mappings during bulk copy.

Classes removed in v6.0

**Comment by tanbchr** [comment]
Can you provide an example on how to perform the column mappings in the bulk.

Let's say that I have a class like this:

public class A
{
	public string Id {get;set;}
	public string Description {get;set;}
}

I want to bulk objects of type A into a table defined like this:

CREATE TABLE [dbo].[Foo](
	[FOO_ID] [nvarchar](45) NOT NULL,
	[FOO_DESC] [nvarchar](45) NULL
)

How do you perform the mapping?

BTW I'm using version 5.2.10.

Thanks!

**Comment by jonwagner** [comment]
Some options:

1. Tag the columns:

```
public class A
{
[Column("FOO_ID")]
public string Id {get;set;}
[Column("FOO_DESCRIPTION")]
public string Description {get;set;}
}
```

2. Programmatically add mappings: https://github.com/jonwagner/Insight.Database/wiki/Customizing-Object-Mapping

**Comment by tanbchr** [comment]
I already thought of using those two methods, however is there another way to achieve it?

I'm trying to do it like this but I can't make it work:

```
connection.BulkCopy("dbo.Foo"), items, configure: (InsightBulkCopy bulk) =>
                {
                    bulk.BatchSize = 1000;
                    bulk.BulkCopyTimeout = 0;
                    var sqlBulk = (SqlBulkCopy)bulk.InnerBulkCopy;
                    sqlBulk.ColumnMappings.Add("Id", "FOO_ID");
                    sqlBulk.ColumnMappings.Add("Description ", "FOO_DESCRIPTION");
                });
```
It's like what's explained in [here](https://github.com/jonwagner/Insight.Database/wiki/Bulk-Copy-with-Objects) in the wiki.

Thank you

**Comment by jonwagner** [comment]
As I mentioned above, that feature was never implemented in 5.x and was removed entirely in 6.x

**Comment by tanbchr** [comment]
Ok Thank you Jon!
