### ISSUE TITLE
Inserts with complex list of objects

### ISSUE THREAD

**Issue by skuvnar** [jonwagner/Insight.Database#245]
Hi there just wondering if there is a way to do inserts for lists of complex objects. For example, I have a Person object with the following structure:
```
-string PersonName
-int PersonAge
-List<Address> addresses
```

Now I want to do inserts with a collection of 'persons' that also have collections of addresses. Could you please tell me if theres a good way to do this with Insight?

Many thanks

**Comment by kevinsea** [comment]
Currently is it only possible to send a single tvp/list via Insight.  You'd need to make 2 calls to do this.

**Comment by jonwagner** [comment]
It depends...

With SQL server you can define a proc like:

    CREATE PROC Insert_Thing (name varchar, age int, addresses TABLETYPE)

And map that to:

    void InsertThing(Thing t);

Although I have this nagging thought in my head that there's a compatibility setting somewhere to control whether we blow apart insert fields like that. But I'm pretty sure it works.

**Comment by kevinsea** [comment]
I was looking into an enhancement and ran across the code that does this.  What Jon describes seems to be supported:

					// special handling for table parameters - replace them with list parameters
					// note that we may be modifying the parameters collection, so we copy the list here
					var provider = InsightDbProvider.For(cmd);
					foreach (var p in cmd.Parameters.OfType<IDataParameter>().Where(p => provider.IsTableValuedParameter(cmd, p)).ToList())
					{
						// if any parameters are missing table parameters, then alert the developer
						if (p.Value == null)
							throw new InvalidOperationException(String.Format(CultureInfo.InvariantCulture, "Table parameter {0} must be specified", p.ParameterName));

						// convert the value to an objectreader
						DbParameterGenerator.ListParameterHelper.ConvertListParameter(p, p.Value, cmd);
					}

**Comment by kevinsea** [comment]
I think this has been addressed, if not please reopen it.
