### ISSUE TITLE
InsertSql SELECT SCOPE_IDENTITY not updating INT property on object instance

### ISSUE THREAD

**Issue by elanbar** [jonwagner/Insight.Database#246]
I am on version 5.2.7.0 and running into the same problem as described in issue #5. The primary key and identity column on my table is INT datatype. The property in my object class is of type "int". The identity value does not get updated to the object instance property. When I change the type of the property in my object class to decimal the identity value gets correctly updated to the property on my object instance.

**Comment by kevinsea** [comment]
Does this resolve your issue?

http://stackoverflow.com/questions/1001854/how-do-i-cast-scope-identity-to-int

**Comment by kevinsea** [comment]
My guess is that that when do the cast you are doing it as 'CAST (...) AS ID' and you doing the simple SELECT SCOPE_IDENTITY() without the AS ID.  That return column name is needed for the mapping per the docs.  Here are the two tests I wrote that show it's currently working correctly (these are a simple variant of some existing tests in the solution, so you can view the source to see GetSample, etc):

	[Test]
	public void TestInsertWithIDReturn_ScopeIdentity_SQL()
	{
		using (DbConnectionWrapper c = Connection().OpenWithTransaction())
		{
			var beer = Beer.GetSample();
			c.InsertSql("INSERT INTO[dbo].[Beer] ([Name], [Style]) VALUES(@Name , @Style ); SELECT SCOPE_IDENTITY() AS [Id]", beer);
			beer.VerifySample();  //this confirms the Id is set
		}
	}

	[Test]
	public void TestInsertWithIDReturn_ScopeIdentity()
	{
		using (var c = Connection().OpenWithTransaction())
		{
			var beer = Beer.GetSample();
			c.Insert(Beer.InsertProcScopeIdentity, beer);  // the proc looks just like the sql above
			beer.VerifySample();
		}
	}

If you are still having issues, please provide some code so we can see what's going on.

**Comment by kevinsea** [comment]
@elanbar please review the tests in #273 that show things work as expected.  If you feel like there is still an issue, please reopen with code for a failing test case.

Thanks!

Kevin
