### ISSUE TITLE
Avoid unnecessary SqlInsightDbProvider.AddjustParameters errors.

### ISSUE THREAD

**Issue by arbitrix** [jonwagner/Insight.Database#247]
When calling a stored procedure, SqlInsightDbProvider.AddjustParameters fails if:

1. The user does not have SELECT permission on the sys* tables being queried.
2. The database is SQL Server 2000 in which 'syscolumns' and friends need to be queried instead of 'sys.parameters'.

The attached patch compiles and works fine in my limited testing. It gracefully falls back to a SQL Server 2000-compatible query if sys.schemas does not exist and it also ignores permission denied errors if they arise.

I am unable to run all the Insight.Database unit tests, nor am I able to test anywhere other than .Net 45. But perhaps this is a useful change nonetheless.

[SqlInsightDbProvider.txt](https://github.com/jonwagner/Insight.Database/files/159171/SqlInsightDbProvider.txt)

**Comment by kevinsea** [comment]
Hmm, SQL 2000 won't run on anything higher than Windows 2003 which is no longer supported by Microsoft.  I don't think we want to be adding support at this time.

I'm also reluctant to silently eat the sys table permission problem...getting that data and using itto refine what's passed in to the store procedure is a valuable part of Insight.

**Comment by kevinsea** [comment]
I'm going to close this one.  Arbitrix if you feel strongly about this one,  please re-open it and we can raise it to Jon for further consideration.

Best,

Kevin
