### ISSUE TITLE
NodaTime support

### ISSUE THREAD

**Issue by nzbart** [jonwagner/Insight.Database#249]
We've been using Insight.Database for a long time now, and love it. However, it doesn't seem to play well with another indispensable library that we also use - NodaTime. Would it be possible to add support for this, even if it's in a separate, optional library to avoid taking a dependency?

**Comment by kevinsea** [comment]
Hi,

You should be able to handle this by implementing your own serializer to turn it into the appropriate type.  Check out the wiki's 'Data Type' section for a page on Object Serialization.

Also, check out the test code for more working examples:  Insight.Tests/Serialization.cs has several good examples.

When you implement the serializer post it in this issue so others can benefit.

**Comment by roryprimrose** [comment]
I've looked at this last year and am blocked on an issue with using NodaTime.Instant in a table parameter. See #217
