### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by rcsprakash** [jonwagner/Insight.Database#251]
Hi,
I have seen the document  and followed it, but the document seems wrong
The syntax is wrong(in bold) and parameter named as "idColumns" but in code its is "splitColumns"
var mapping = new OneToOne<Serving, Beer>(**idColumns**: new Dictionary<Type, **string<(**)
{
    { typeof(Serving), "ServingID**",}**
    { typeof(Beer), "BeerID" }
});

Kindly correct it.
Document url :https://github.com/jonwagner/Insight.Database/wiki/Record-Readers 

Thanks,
Suria

**Comment by josephyanks** [comment]
You can also make the changes yourself by going to the page, upper right hand corner -> Edit.

**Comment by rcsprakash** [comment]
done
