### ISSUE TITLE
Conditional calls to stored procedure from a stored procedure

### ISSUE THREAD

**Issue by steelfaith** [jonwagner/Insight.Database#253]
I have a procedure that uses an IF Exists clause and inside the begin it calls another procedure that has 4 result sets.

If the procedure goes into the if clause all is good, but if it does not then my results sets are missing the 4 from the procedure that is not called, and the rest of the result sets are shifted and errors.

I'm probably going to make that call not conditional and if the input parameter is null have it return empty sets, but its coding around what I see as an issue.

Is there some way to validate a result set is what you expect?  Other than writing the db access code myself of course.

**Comment by kevinsea** [comment]
Hi,

Is this heirarchical data or just 4 flat sets of objects? If they are flat
you could count the number of results and bind accordingly.  If it's
heirarchical, you are getting a ton of functionality for free, it seems
like a reasonable trade off that the results are consistent :)

Or, what about making the conditional result set come up last?

Best,

Kevin
