### ISSUE TITLE
Insight.Database.Providers.OracleManaged NuGet package spec (v5.2.7) still requires odp.net.managed

### ISSUE THREAD

**Issue by Decklock** [jonwagner/Insight.Database#254]
I believe the actual Insight.Database.Providers.OracleManaged code was updated to use the official Oracle.ManagedDataAccess driver (in Issue #205), but the NuGet package itself still lists odp.net.managed as a dependency in the Insight.Database.Providers.OracleManaged.nuspec file. Thanks!

**Comment by Jaxelr** [comment]
There is a PR created to address this issue  #244

**Comment by kevinsea** [comment]
Closing as duplicate to #244
