### ISSUE TITLE
Getting SQL text

### ISSUE THREAD

**Issue by tshepherdcirrus** [jonwagner/Insight.Database#256]
Is it possible to get the actual text of the sql statement that is going to be executed or the sql that was just executed for logging/debug purposes? I know i can use SQL Profiler for debugging, it's more for logging.

**Comment by kevinsea** [comment]
Hi,

Would the Glimpse Provider do what you need?  https://github.com/jonwagner/Insight.Database/wiki/Glimpse-Provider ...or the MiniProfiler?

**Comment by tshepherdcirrus** [comment]
Yes actually it would - another reason it chose insight becasue of those
providers

**Comment by kevinsea** [comment]
Great.  Closing #256.
