### ISSUE TITLE
Prefixing Stored Procedure Parameters

### ISSUE THREAD

**Issue by shoaibshakeel381** [jonwagner/Insight.Database#259]
Hi, My stored procedures parameters are prefixed with `p_` string. So if I have a class `A`

`class A {
     public string propA { get; set; }
}`

And I pass an object of this class to stored prcedure. 

`CREATE PROC GetBeerByType @p_type [varchar] AS SELECT * FROM Beer WHERE Type = @p_type GO`

how should I prefix 'p_' to my property names.

**Comment by tshepherdcirrus** [comment]
I think you need this: https://github.com/jonwagner/Insight.Database/wiki/Customizing-Object-Mapping
