### ISSUE TITLE
Passing List of SqlParameters to Query, Execute Methods

### ISSUE THREAD

**Issue by shoaibshakeel381** [jonwagner/Insight.Database#260]
Can I pass a list of SqlParameters in place of `parameter` for Query, Execute and other methods?

**Comment by kevinsea** [comment]
Hi, the documentation covers passing parameters well.  See

https://github.com/jonwagner/Insight.Database/wiki/Executing-SQL-Commands

**Comment by shoaibshakeel381** [comment]
Provided link only uses anonymous object for parameters not SqlParameter.

**Comment by AndrewFreese** [comment]
I think the answer is no.
