### ISSUE TITLE
Configuration to output varchar declaration instead of nvarchar

### ISSUE THREAD

**Issue by diltonE** [jonwagner/Insight.Database#262]
When executing direct sql i.e. Database.ExecuteSql any string type parameter is declared as nvarchar in the final sql.

Can Insight DB be configure to output string type parameters as varchar?

Instead of outputting @aString nvarchar(20) output this @aString varchar(20).

**Comment by kevinsea** [comment]
Stored procedures give us the information to decide varchar vs nvarchar.  There really isn't good option for dynamic sql.  I'm not sure what kind of problem nvarchar creates, but consider a stored procedure for this type of control.
