### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by Jaxelr** [jonwagner/Insight.Database#264]
Haven't seen any activity since Sept 2015. I know this could be considered spam, so my apologies for those bothered, but for fellows who might consider this project in a prod environment, such as myself, its worth finding out.

**Comment by tshepherdcirrus** [comment]
I too am a little worried about this - Jon (the author) has not committed anything for a number of months now and there are a number of pull requests that haven't been actioned. This is a great little mapper tool and I don't want to see it die. We are embarking on a re-write and were looking to incorporate a mapper - I selected this tool after researching many others, based on it's mapping capabilities and its focus on stored procedures as our system is very centred around stored sprocs. We don't really want to write our own :(

**Comment by andreabaldin** [comment]
Yep, I'm worried too.
Furthermore I really would enjoy with a .Net Core version...

**Comment by tshepherdcirrus** [comment]
I'd consider taking up the project but a) I don't want to do that on my own and b) I'd like to get Jon's permission :)

I've looked through the code and while some of it is a bit deeper than my experience allows, a challenge is always fun!

**Comment by jonwagner** [comment]
Hey gang –

Let me apologize for not being fully engaged in the project for a while. I took a job that has a large time commitment and not a lot of development work. Worse yet, the code I have been able to do is on a mac, in ruby *shudder*, so I can’t just easily switch over and work on Insight when I find spare time.

It’s definitely time to gather a larger team on the project if we want to keep it moving. I put a lot of time in the project, and I definitely want it to keep it alive!

I have a vacation coming up the week of Aug 22, and I’d love to get the project rebooted then. If I can get some volunteers, I know that I can coordinate fixes, development, and upgrades. And if we get all of that in working shape, I might even be able to find time to do a bunch of coding myself.

If I get 2-3 volunteers to email me (jonwagner at Hotmail) by 8/22, I’ll organize getting the project back on track. Tell me about yourself and how you think you can help out, and I’ll put together a plan.

I’ll probably need some help getting by toolset back up to modern, and I really want to put out a .NET Core version so the whole world can do ORMs right.

**Comment by tshepherdcirrus** [comment]
Hi Jon - sent you an email to that Hotmail address but it doesn't appear to be getting thru

**Comment by Jaxelr** [comment]
@tshepherdcirrus I emailed jon right now and i didnt get any unavailable reply, so maybe try again?

**Comment by tshepherdcirrus** [comment]
It was a "delayed delivery" type message - I haven't received one of those today so I assume that my email has gotten through.

**Comment by jonwagner** [comment]
I have emails from Bojan, Keith, and Jaxel.

tshepherdcirrus - I will track down your info.
I have a nice new copy of Vmware fusion and windows 10 on my mac :( so now I can get started. I'll email you all this weekend.

Thanks for the help!


On Aug 12, 2016, at 3:18 AM,  <notifications@github.com<mailto:notifications@github.com>> wrote:


It was a "delayed delivery" type message - I haven't received one of those today so I assume that my email has gotten through.

-

**Comment by Jaxelr** [comment]
@jonwagner Email a few of us and we are gonna help out with keeping the project going forward.
