### ISSUE TITLE
Insight.Database should be on awesome-dotnet lists

### ISSUE THREAD

**Issue by lawrencek76** [jonwagner/Insight.Database#270]
[Read this blog](https://channel9.msdn.com/coding4fun/blog/Hunt-for-Your-Libs-Here-at-AwesomeNET) this morning and realized Insight is not on the list. 

https://dotnet.libhunt.com/

We need to get it on there and then voted up to be on the official list
https://github.com/quozd/awesome-dotnet

**Comment by Jaxelr** [comment]
@lawrencek76 You gonna do the PR? If so, we can vote it in, i think the project satisfies the criteria. :+1:

**Comment by lawrencek76** [comment]
I put the [pull request](https://github.com/quozd/awesome-dotnet/pull/370) in.  We'll see what happens.

**Comment by Jaxelr** [comment]
It has been [merged](https://github.com/quozd/awesome-dotnet/pull/370) 👍
