### ISSUE TITLE
Automated Integration Tests

### ISSUE THREAD

**Issue by jonwagner** [jonwagner/Insight.Database#271]
It would be nice if I didn't have to approve builds. In order to do that, we'd want auto-builds running. I've used CircleCI for linux builds. There's probably something better out there.

**Comment by Jaxelr** [comment]
[AppVeyor](https://www.appveyor.com/) is free for open source projects.

**Comment by jonwagner** [comment]
AppVeyor looks pretty good for windows projects. I think the hardest part will be installing the database drivers on the servers. At the minimum we can use it for testing the base build and not the drivers.

**Comment by jonwagner** [comment]
Deferring until I have more time.
