### ISSUE TITLE
Revert / Complete VS2015 Debugger fix for InternalsVisibleTo

### ISSUE THREAD

**Issue by jonwagner** [jonwagner/Insight.Database#277]
For v5.2.8, we added a debugger workaround for InternalsVisibleTo.

In v6.0, we'll officially change the name of the dynamic assemblies and we can remove the debug-only code.

See:

https://github.com/jonwagner/Insight.Database/pull/272/files

**Comment by kevinsea** [comment]
I'm in this bit of code for the Core stuff, I'll take care of this.

**Comment by jonwagner** [comment]
Make sure it's a separate commit. :)

On Sep 8, 2016, at 5:50 PM, Kevin Callahan <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm in this bit of code for the Core stuff, I'll take care of this.

-

**Comment by jonwagner** [comment]
Done in 6.0
