### ISSUE TITLE
Switch to a MIT license?

### ISSUE THREAD

**Issue by kevinsea** [jonwagner/Insight.Database#285]
Insight currently uses the very permissive MS-PL license.  

.Net Core, Mono and even a read-only reference version of .Net 4.6 are all licensed with a similarly permissive MIT [license](https://opensource.org/licenses/MIT).  It seems Microsoft has shifted its own software to the MIT license because it compatible most other other open source licenses.  And MIT allows .Net 4.6, .Net Core and Mono to more easily share code.

Is there any downside to changing the license with Insight v6?

**Comment by Jaxelr** [comment]
:+1:

**Comment by jonwagner** [comment]
Done in 6.0
