### ISSUE TITLE
Upgrade to NUnit 3

### ISSUE THREAD

**Issue by kevinsea** [jonwagner/Insight.Database#289]
.Net Core requires that we upgrade from Nunit 2 to 3. There are a few breaking changes:
- Syntax for expected exceptions
-  I think the [SetUp] attribute needs to be changed to [OneTimeSetUp]
  http://bartwullems.blogspot.com/2015/12/upgrading-to-nunit-30-onetimesetup.html

Changes for core should come in via another branch but fwiw good reading on that here https://github.com/nunit/dotnet-test-nunit

**Comment by jonwagner** [comment]
Done in 6.0
