### ISSUE TITLE
Unwrapping and serialising a generic type

### ISSUE THREAD

**Issue by Neaox** [jonwagner/Insight.Database#291]
Hi there,

We have a generic type (for example `Class<T>`) with an inner value of type `T`. Is there an easy way to, within a IDbObjectSerializer, extract the value and pass it on for further serialisation by the registered `DbSerializationRules`?

Is there an easy way to accomplish this?

**Comment by jonwagner** [comment]
I think we need more information about your use case in order to help you. If you still have the issue, please post some more details and reopen the case.
