### ISSUE TITLE
Large CLOB insert not supported?

### ISSUE THREAD

**Issue by phylocter** [jonwagner/Insight.Database#294]
Hi,

I have a large XML string that I want to insert in the database as a CLOB. I get the following error:
"SQL Error: ORA-01704: string literal too long"
Is there a function or a way in Insight to bypass the 4000 characters problem of inserting a string in a CLOB?

**Comment by kevinsea** [comment]
Are you using a dynamic sql or a stored procedure?

**Comment by jonwagner** [comment]
It looks like you are using Oracle.

Try using the `xmltype` or `varchar(MAX)` types.

**Comment by jonwagner** [comment]
If you still have the issue, please post some more details and reopen the case.
