### ISSUE TITLE
RecordSet Attribute Null Column

### ISSUE THREAD

**Issue by carand315** [jonwagner/Insight.Database#300]
I have a issue
SP->
`SELECT A.*, B.*, othervalue FROM A INNER B.....`

where...
A and B are two classes one-to-one relationship

```
Class A {
     Property B

     [Column("othervalue ")]
     Property CustomValue
}
```
It works `CustomValue `property, doesn't `Property B` (null), so add 
```
[RecordSet(typeof(A),RecordSet(typeof(B))]  
Class A {...
```
 then
It works `Property B`, BUT doesn't Property `CustomValue `(Null)

Thanks for help.

**Comment by jonwagner** [comment]
Insight expects all of the fields from an object to be read before moving on to another object.

In your query:

    SELECT A.*, B.*, othervalue

once the reader starts reading `B.*`, it won't go back to your A fields.

Change your query to:

    SELECT A.*, othervalue, B.*

And it should work
