### ISSUE TITLE
.NET version concurrency problems

### ISSUE THREAD

**Issue by ingeniousclown** [jonwagner/Insight.Database#301]
For reasons beyond my control, much of my application is limited to the .NET 3.5 version of Insight.  Also for reasons beyond my control, this must live in the GAC which is always taken over a local copy.  We have other services that may use .NET 4+ and would like to use Insight for .NET 4.5+ for these other services, but the inclusion of 3.5 in the GAC and the fact that each differently targeted build uses the same exact version number is preventing us from being able to do this without causing issues in one or the other.

I'd love to see each build have a different version number.  Is this possible?

**Comment by jonwagner** [comment]
I believe that each version of the framework has it's own GAC. There shouldn't be a conflict unless you install assemblies in the wrong GAC. (But i could be wrong here.)

http://stackoverflow.com/questions/2660355/net-4-0-has-a-new-gac-why

**Comment by jonwagner** [comment]
If you still have the issue, please post some more details and reopen the case.
