### ISSUE TITLE
NET Standard 2.0 - run tests under netstandard2.0 instead of netcoreapp2.0

### ISSUE THREAD

**Issue by jonwagner** [jonwagner/Insight.Database#310]
I'm not sure if you can get test cases to run under netstandard. I was able to run the test cases under netcoreapp2.0, and that tests the netstandard2.0 libraries, but I would be happier if it runs on the same platform moniker.

Investigate whether this is possible.

**Comment by andymac4182** [comment]
From my understanding due to `netstandard` being an interface you are meant to run your tests against the various runtimes. I am currently testing our libraries against netcoreapp1.0 and net462. XUnit runs the tests once for each implementation.

**Comment by jonwagner** [comment]
Yeah, I'm pretty sure that's the case, but the whole interface/implementation story is a bit of a jumble so I wanted to double check before thinking I had it right.

**Comment by jonwagner** [comment]
As expected, .NET Standard is just the API definition, and if you try to execute code on it, you won't have any supporting libraries.
