### ISSUE TITLE
MiniProfiler - MiniProfiler for NET Standard should use a stable package

### ISSUE THREAD

**Issue by jonwagner** [jonwagner/Insight.Database#315]
The MiniProfiler provider is currently using a pre-release package for NET Standard support.

Use a stable package prior to release.

**Comment by jonwagner** [comment]
MiniProfiler seems to be under active development. They are tracking a v4 release with this issue:

https://github.com/MiniProfiler/dotnet/issues/144

**Comment by jonwagner** [comment]
No news from the MiniProfiler team. Closing support for MiniProfiler.

**Comment by Jaxelr** [comment]
Mini Profiler version 4.0.0 is out on myget, which means a release is on the horizon https://www.myget.org/feed/miniprofiler/package/nuget/MiniProfiler

**Comment by jonwagner** [comment]
It looks like 4.0 has been posted to nuget, so we can tackle this one now.

**Comment by jonwagner** [comment]
This will be in 6.2.3
