### ISSUE TITLE
MySql - Support NET Standard 2.0

### ISSUE THREAD

**Issue by jonwagner** [jonwagner/Insight.Database#316]
The MySql 7.0 library supports NET Standard (currently in a preview build), but does not implement DeriveParameters.

Implement DeriveParameters for MySql (possibly from other open-source code) and support NET Standard 2.0

**Comment by jonwagner** [comment]
This has been implemented in the 6.0 branch. Waiting for the 7.x package to be released.

**Comment by jonwagner** [comment]
Updated MySQL to 8.0.8-dmr preview release

**Comment by eakova** [comment]
+1

**Comment by jbright** [comment]
@jonwagner is this still an open issue? I'm getting 

```
warning NU1701: Package 'Insight.Database.Providers.MySQL 6.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
```

In a simple Hello World app. (I can connect to my MySql DB though).

**Comment by jonwagner** [comment]
The MySQL .NET Core drivers are still in preview. It looks like .NET Core 2 is attempting to fall back to the .NET 4.6.1 drivers. That may or may not work, depending on what apis the driver users.

**Comment by jonwagner** [comment]
Finally supported in 6.1.2
