### ISSUE TITLE
OracleManaged - support NET Standard 2.0

### ISSUE THREAD

**Issue by jonwagner** [jonwagner/Insight.Database#317]
The OracleManaged provider version 12 does not yet support .NET Core. Find a version that does.

**Comment by jonwagner** [comment]
It looks like Oracle is planning on releasing .NET Standard 2.0 drivers at the end of 2017.

http://www.oracle.com/technetwork/topics/dotnet/tech-info/odpnet-dotnet-core-sod-3628981.pdf

**Comment by jonwagner** [comment]
Still no news from Oracle.

**Comment by jonwagner** [comment]
Oracle is still behind, and their managed driver doesn't support basics like bulk copy. They should lose business for this.

**Comment by andymac4182** [comment]
https://twitter.com/OracleDOTNET/status/971179206750060544

It seems they have added some support and nuget now

**Comment by jonwagner** [comment]
I should have some time to test it before i drop 6.2

On Mar 8, 2018, at 12:53 AM, Andrew McClenaghan <notifications@github.com<mailto:notifications@github.com>> wrote:


https://twitter.com/OracleDOTNET/status/971179206750060544

It seems they have added some support and nuget now

**Comment by jonwagner** [comment]
Hooray(?)

v6.2 now has Insight.Database.OracleManaged.Core, which uses Oracle.OracleManaged.Core. The Oracle library is still in beta, so our provider is marked as pre-release, but it looks like it should run fine.

Enjoy.
