### ISSUE TITLE
Convert Test Databases from Vagrant to Docker

### ISSUE THREAD

**Issue by jonwagner** [jonwagner/Insight.Database#320]
Currently the Vagrant test databases run in one giant image (about 10GB). See if docker images are available and convert the test framework to use docker.

Bonus points to use the sql server on linux container so we don't even need a sql server to run tests.

By only using nuget packages and running with docker containers, we should be able to set up some automated testing for at least part of the project.

**Comment by resnikb** [comment]
For SQL Server, using LocalDB might be an easier option, either directly, or through a wrapper such as https://www.nuget.org/packages/System.Data.SqlLocalDb/

**Comment by Jaxelr** [comment]
It depends on the installation selection of Visual Studio. Chances are it is see -> https://stackoverflow.com/questions/42774739/how-to-install-localdb-2016-along-with-visual-studio-2017 for the 2017 version

**Comment by jonwagner** [comment]
Completed in the 6.0 branch.

I used docker for all of the dbs (sqlserver, db2, postgres mysql, oracle), so you can run the tests on any platform now. (at least the core tests)
