### ISSUE TITLE
AsParallel<T> is not working with interfaces inherited from IDbConnection and IDbTransaction

### ISSUE THREAD

**Issue by Kladzey** [jonwagner/Insight.Database#322]
I have interface that I usually use with transactions via OpenWithTransactionAs<T>. Now in some places I need to use it for multi-threaded connections. When I'm calling AsParallel<T> for it, next exception is raised:
```
System.InvalidOperationException occurred
  HResult=0x80131509
  Message=DBTEST.IRepository is inaccessible to Insight.Database. Make sure that the interface is public, or add [assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Insight.Database")] to your assembly. If the interface is nested, then it must be public to the world, or public to the assembly while using the InternalsVisibleTo attribute.
  Source=Insight.Database
  StackTrace:
   at Insight.Database.CodeGenerator.InterfaceGenerator.CreateImplementorOf(Type type, Boolean singleThreaded)
   at Insight.Database.CodeGenerator.InterfaceGenerator.<>c__DisplayClass11.<GetImplementorOf>b__10(Type t)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Insight.Database.CodeGenerator.InterfaceGenerator.GetImplementorOf(Type type, Func`1 connectionProvider, Boolean singleThreaded)
   at Insight.Database.DBConnectionExtensions.AsParallel(Func`1 provider, Type type)
   at Insight.Database.DBConnectionExtensions.AsParallel[T](Func`1 provider)
   at Insight.Database.ConnectionStringSettingsExtensions.AsParallel[T](ConnectionStringSettings settings)
   at DBTEST.Program.Main(String[] args) in D:\Coding\Main\MMCRM\DBTEST\Program.cs:line 20

```

Code example:
```
using System;
using System.Configuration;
using System.Data;
using System.Threading.Tasks;
using Insight.Database;

namespace DBTEST
{
  public interface IRepository : IDbConnection, IDbTransaction
  {
    Task<int> SomeQueryAsync();
  }

  class Program
  {
    static void Main(string[] args)
    {
      var settings = new ConnectionStringSettings("test", "Data Source=SomeDb;Initial Catalog=SomeDb;Integrated Security=True;Asynchronous Processing=true");
      using (var r = settings.OpenWithTransactionAs<IRepository>())
        Console.WriteLine("OpenWithTransactionAs " + r); // works well
      Console.WriteLine("As " + settings.As<IRepository>()); // works well too
      Console.WriteLine("AsParallel " + settings.AsParallel<IRepository>()); // throws "is inaccessible to Insight.Database" exception
      Console.ReadKey();
    }
  }
}
```
I have checked it with 5.2.7 and 5.2.9 versions.
If it's expected behavior, maybe more convenient exception message and some doc update are required?

**Comment by jonwagner** [comment]
It looks like the generated class isn't being exposed to further code generation. We should be able to fix that by making the generated repository class public or adding the internalsvisibleto attribute internally.

**Comment by Jaxelr** [comment]
Even though the error message is of inaccessibility, the exception thrown by Insight is the following: 

{"Method 'get_ConnectionString' in type 'DBTEST.IRepositorye01e7a16-92ef-4424-8e69-17f6df96b7a0' from assembly 'Insight.Database.DynamicAssembly, Version=5.2.9.0, Culture=neutral, PublicKeyToken=f35c6ef87e515afc' does not have an implementation.":"DBTEST.IRepositorye01e7a16-92ef-4424-8e69-17f6df96b7a0"}	

The error happens on this line: https://github.com/jonwagner/Insight.Database/blob/master/Insight.Database/CodeGenerator/InterfaceGenerator.cs#L140

The LoadException on line 146 traps the original and re-throws the message seen above.

**Comment by jonwagner** [comment]
I see what you're doing.

An interface wrapped in `AsParallel<T>` is designed to be used on multiple threads, and expects to use multiple connections. It automatically creates new connections from the connectionstringsettings, so it shouldn't derive from IDbConnection or IDbTransaction.

This code works properly:

	public interface IRepository322
	{
		[Sql("SELECT 1")]
		Task<int> SomeQueryAsync();
	}

	[TestFixture]
	public class TestIssue322 : BaseTest
	{
		[Test]
		public void Test()
		{
			var repo = System.Configuration.ConfigurationManager.ConnectionStrings["Test"].AsParallel<IRepository322>();
			var i = repo.SomeQueryAsync().Result;
		}
	}

I'll add a different exception for this case.

**Comment by jonwagner** [comment]
v5.2.10 has a small fix that allows the interface to be derived from IDBConnection or IDbTransaction.
