### ISSUE TITLE
Does the BulkCopy feature support Oracle Managed Driver

### ISSUE THREAD

**Issue by design0er** [jonwagner/Insight.Database#324]
hello.Does the BulkCopy feature support Oracle Managed Driver? or it just support the oracle unmanaged driver?

**Comment by jonwagner** [comment]
Oracle.ManagedDataAccess.Client.OracleConnection does not provide a BulkCopy method. You will have to use the unmanaged driver if you want to use BulkCopy.

**Comment by design0er** [comment]
thanks a lot.
