### ISSUE TITLE
Unable to use insight for .netcoreapp

### ISSUE THREAD

**Issue by tancndi** [jonwagner/Insight.Database#326]
I created a .NET Core Web API and when i install insight from nuget i have the following issue :

```
Installing Insight.Database.Core 5.2.10.
Package Insight.Database.Core 5.2.10 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Insight.Database.Core 5.2.10 supports:
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
One or more packages are incompatible with .NETCoreApp,Version=v1.0.
Package restore failed. Rolling back package changes for 'MyApi'.
```

I tried that for Insight.Database.Core and Insight.Database and both gave me the same issue. 
Is there a version compatible with .netcoreapp1.0 so far or not ?

**Comment by jonwagner** [comment]
You can use the prerelease 6.0 version with core 1.0/2.0

On Jul 17, 2017, at 6:41 PM, tancndi <notifications@github.com<mailto:notifications@github.com>> wrote:


I created a .NET Core Web API and when i install insight from nuget i have the following issue :

Installing Insight.Database.Core 5.2.10.
Package Insight.Database.Core 5.2.10 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Insight.Database.Core 5.2.10 supports:
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
One or more packages are incompatible with .NETCoreApp,Version=v1.0.
Package restore failed. Rolling back package changes for 'MyApi'.


I tried that for Insight.Database.Core and Insight.Database and both gave me the same issue.
Is there a version compatible with .netcoreapp1.0 so far or not ?

**Comment by tancndi** [comment]
When can we have the official release 6.0 version ? 
We are actually using Insight.Database  in a lot of our .Net framework project and are migrating them to .Net core. and we are wondering if we should wait for the release or keep working with .net framework.

**Comment by jonwagner** [comment]
I'm mostly waiting for either someone to do significant testing with core 1, or for core 2 to be released.

If you get your app and tests to run, we can do an official 6.0 build.

On Jul 18, 2017, at 12:23 PM, tancndi <notifications@github.com<mailto:notifications@github.com>> wrote:


When can we have the official release 6.0 version ?
We are actually using Insight.Database in a lot of our .Net framework project and are migrating them to .Net core. and we are wondering if we should wait for the release or keep working with .net framework.

**Comment by tancndi** [comment]
I download the version 6.0.0-alpha2 of the project to build the dlls but i have some errors on visual studio 
`Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0)' for '.NETCoreApp,Version=v2.0'`

I'm i using the bad version of .netCore ? Or is there a way to have the dlls without building the whole project from visual studio ?

**Comment by tancndi** [comment]
- And I notice that the conditional compilation symbols in the project properties are duplicated every time i build the project is that normal ?
- I also have a problem with some symbols as `NO_FULL_SYSTEM_DATA_IMPLEMENTATION` is there some settings to do to make it work
- finally i know that `DataTable`  does not work with .netcore 1.0 and is there some settings to do make the solution work ?

**Comment by jonwagner** [comment]
You should be able to use the alpha2 packages in nuget.

https://www.nuget.org/packages/Insight.Database/6.0.0-alpha2
https://www.nuget.org/packages/Insight.Database.Core/6.0.0-alpha2

If you want to build the code, you will need to install .NET Core 2 Preview 2.

**Comment by tancndi** [comment]
Thank you.  But we finally get back to .Net framework. But i installed the alpha2 packages from nuget and it worked well for what i needed (the mapping and bulk insert.)
