### ISSUE TITLE
DataReader dont close automatically sometimes

### ISSUE THREAD

**Issue by LiquidzDEV** [jonwagner/Insight.Database#327]
Hello,

sometimes i have a Problem that the DataReader dont close itself after i call a Stored Procedure through an Interface.
It is totally random, sometimes it works for days, sometimes only for a few hours.

After the Exception occurs, all calls after that have the same Exception, the Datareader wont close until i close the Programm.

Is there a way to manually close the connection when the Error occurs?

![bug](https://user-images.githubusercontent.com/20011008/28502382-5a0ebd4e-6ff1-11e7-9e46-0fc5a6d42f98.PNG)

**Comment by jonwagner** [comment]
It sounds like you are using the same connection for multiple threads. If you use a connection across multiple threads, you will get random "already open" errors.

There are a few ways to safely use interface connections in your code:

*Create a new connection for each request*

    ...
    var inventory = new MySqlConnection(connectionString).As<IInventory>();
   inventory.GetInventory();
    ...

*Use `AsParallel` to tell Insight to create a new connection for each method call*

   ...
   private static inventory = new MySqlConnection(connectionString).AsParallel<IInventory>();
   ...
   inventory.GetInventory();
   ...

**Comment by LiquidzDEV** [comment]
Thanks for your help!

When i use AsParallel or create a new connection for each request does this affect the Performance noticeable?
Sometimes i send about 1000 queries to the Database when i save all the stuff.

**Comment by jonwagner** [comment]
The connections are returned to the .NET connection pool, so you shouldn't see a noticeable difference, but you should profile your code anyway.

**Comment by LiquidzDEV** [comment]
Okay thank you, i will look into profiling my code.
