### ISSUE TITLE
Support for setting TypeName for TVP

### ISSUE THREAD

**Issue by andymac4182** [jonwagner/Insight.Database#328]
It appears that if you can set the `TypeName` manually support for TVP in SQL without a stored procedure would be possible.

https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/table-valued-parameters

**Comment by jonwagner** [comment]
For `SELECT * FROM @mytabletype` + `new { mytabletype = List<Foo>}`

* in v5.x, Insight will attempt to map it to the [FooTable] type.
* in v6.x (alpha3 & later), Insight will look for table types that match parametername, classname, then classnameTable. In this case `mytabletype`, `Foo`, `FooTable`

Look for a build soon!

**Comment by andymac4182** [comment]
Thanks!

**Comment by jonwagner** [comment]
I just pushed the official 6.0.0 release (with .net core 1/2 support). You can be the first to download it.

Now it's time for bed. :)
