### ISSUE TITLE
Cannot derive parameters for the stored procedure Assessment_READ. Have you loaded the provider that supports SqlCommand? - v6.0 - 

### ISSUE THREAD

**Issue by andreabaldin** [jonwagner/Insight.Database#330]
Hi Jon,
I'm experiencing the error "Cannot derive parameters for the stored procedure Assessment_READ. Have you loaded the provider that supports SqlCommand?" using the v6.0.  I tested that on a dotnet core project pointing to SQL2008 and SQL2016 DBs with the Auto Interface Implementation.
Can't figure what I'm missing ...

**Comment by jonwagner** [comment]
Try calling SqlInsightDatabaseProvider.RegisterProvider

On Sep 3, 2017, at 1:11 AM, andreabaldin <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Jon,
I'm experiencing the error "Cannot derive parameters for the stored procedure Assessment_READ. Have you loaded the provider that supports SqlCommand?" using the v6.0. I tested that on a dotnet core project pointing to SQL2008 and SQL2016 DBs with the Auto Interface Implementation.
Can't figure what I'm missing ...

**Comment by andreabaldin** [comment]
First of first thanks for your quick response.

Yep, calling the method you suggested   SqlInsightDbProvider.RegisterProvider();    it works !
I missed that given wasn't required for SQLServer on previous version ...

Thanks again for the precious suggestion.
Ciao

**Comment by Jaxelr** [comment]
Closing this then.
