### ISSUE TITLE
Update ValueTuple dependency to 4.4.0

### ISSUE THREAD

**Issue by jamezor** [jonwagner/Insight.Database#333]
The `ValueTuple` package prior to 4.4.0 cannot be referenced by .NET 4.7 Framework projects, which makes using Insight.Database with .NET 4.7 projects a bit tricky (doable, but required messing around with references manually etc).

4.4.0 is all good though so it would be great if Insight.Database could use that instead.

More details at https://stackoverflow.com/a/45598683/220993.

**Comment by jonwagner** [comment]
Sure thing. I need to do a pass through other dependencies for .NET core, so it's about time to do an update.

**Comment by jonwagner** [comment]
This will be in the next build.

**Comment by jonwagner** [comment]
This is fixed in 6.1.0-alpha1. (Posting shortly.)

Please let me know if it works for you.

**Comment by jamezor** [comment]
Looks good! Thank you very much.
