### ISSUE TITLE
Insight Database Nuget version 6.0.0 contains an Empty Assembly

### ISSUE THREAD

**Issue by fomenta** [jonwagner/Insight.Database#334]
I downloaded Nuget version 6.0.0 of Insight database. The dll seems to be invalid.

![image](https://user-images.githubusercontent.com/2394742/31771493-f1a93086-b4a1-11e7-8862-597019a5059b.png)

My projects did not compile anymore. Also, when I checked it using JustDecompile, it is actually an empty class compiled:

![image](https://user-images.githubusercontent.com/2394742/31771553-2822d482-b4a2-11e7-9241-b986ce975b91.png)

**Comment by jonwagner** [comment]
In v6.0, Insight.Database is a stub package that depends on Insight.Database.Core and Insight.Database.Providers.Default. All of the active code has moved into the Core & Providers packages. Check to make sure that nuget has added those packages to your project.

**Comment by fomenta** [comment]
In version 5.2 I used an object called ReliableConnection. When I updated my nuget, the class cannot be found. Where is it located at? on version 6.0, I mean.

**Comment by Jaxelr** [comment]
The class still exists on the Insight.Database.Core project (It was also there on 5.2.*).  A quick search on github shows you where it is: https://github.com/jonwagner/Insight.Database/blob/1704f96d4e7f67753f85dc18bf1c9b8a06811465/Insight.Database.Core/Reliable/ReliableConnection.cs 

as Jon mentioned, make sure you have the correct files related to Insight on your project.

**Comment by fomenta** [comment]
The problem is with ReliableConnection: This is the error I am getting when upgrading nuget on an existing project:

Error CS0246 The type or namespace name 'ReliableConnection' could not be found (are you missing a using directive or an assembly reference?)

**Comment by fomenta** [comment]
Found it!

ReliableConnection class is now under Insight.Database.Core and it was not referenced by the project.

**Comment by Jaxelr** [comment]
Closing Issue.
