### ISSUE TITLE
AutoInterface async out parameters

### ISSUE THREAD

**Issue by steveadoo32** [jonwagner/Insight.Database#335]
Is there anyway to have output parameters using async methods on an auto implemented interface? Or is it only supported on sync methods?

```
public interface IRepository {

    // Invalid C# code.
    Task<Model> InsertAsync(Model model, out int id);

}
```

**Comment by jonwagner** [comment]
Unfortunately, it's not possible in c#:

Here are some options for implementing the behavior that you want:

https://stackoverflow.com/questions/18716928/how-to-write-a-async-method-with-out-parameter

**Comment by tkolo** [comment]
I found that if instead of declaring params directly you wrap them in object, it works as expected
So the above example would have to become:
```
public class InsertParams {
    public Model model { get; set; }
    public int Id { get; set; }
}

public interface IRepository {

    // Invalid C# code.
    Task<Model> InsertAsync(InsertParams @params);

}
```

after awaiting result, `@params.Id` will be set.

**Comment by jonwagner** [comment]
Yes! That will work fine. The library can keep a handle on the input parameter object and fill it in after the query completes. The issue with output parameters is that there is no object that we can keep a handle to.

**Comment by tkolo** [comment]
I'd probably be a good idea to include this information on the wiki. Currently the page about [auto interface implementation](https://github.com/jonwagner/Insight.Database/wiki/Auto-Interface-Implementation) says nothing about how to handle out parameters in async methods, and as async becomes more and more of a de-facto standard in modern applications, it's becoming a crucial problem
