### ISSUE TITLE
Installation Issue.

### ISSUE THREAD

**Issue by mprofitt** [jonwagner/Insight.Database#337]
Installed from NuGet and I am using Insight.Database and Providers.MySql. I am a novice programmer, forgive my ignorance.

`The type or namespace name 'Insight' could not be found (are you missing a using directive or an assembly reference?)`

**Comment by mprofitt** [comment]
I called it, it was ignorance.
I had to add references to Insight.* and System.Data in a XML file.

**Comment by jonwagner** [comment]
good luck!
