### ISSUE TITLE
OneToOne<T> Column Splitting/Documentation/Override

### ISSUE THREAD

**Issue by the-dansan** [jonwagner/Insight.Database#340]
Hi there,

Love the library, have been using it for some time in many projects. Thanks for all the work.

I've been struggling with a pretty frustrating mapping problem when using OneToOne<T> and it's taken me forever to realize that it is apparently due to column order.

I found this documented, though perhaps not clearly enough, in the [Record-Readers](https://github.com/jonwagner/Insight.Database/wiki/Record-Readers) section:

> Go through each column from left to right (or 0 to n).
If the column maps to a property of the first class (Serving), then map it.
If the column does not map to the first class, and the column maps to the second class, then the second class must be starting.
Repeat until the columns are exhausted.

I also found that the example of passing in the custom mapping dictionary using the splitColumns parameter did not override the column order issue.

I don't know how much of this is intentional, but I will supply a suggested change to the docs shortly to make it more obvious here, and (generally) in the [Specifying-Result-Structures](https://github.com/jonwagner/Insight.Database/wiki/Specifying-Result-Structures) section.

**Comment by jonwagner** [comment]
Thanks, Dan. I'm glad that you're finding success with the library. I appreciate any help I can get, particularly around unclear documentation. PR away!
________________________________

**Comment by jonwagner** [comment]
Let me know when you have a doc PR and we'll reopen this.

**Comment by the-dansan** [comment]
Hi Jon --

Sorry for the delay. I have a branch locally two files lightly changed, but
I have no way to get it to you. How would you like me to proceed?

**Comment by jonwagner** [comment]
The easiest way is just to edit the wiki on github. I'm pretty sure the Edit button is available for everyone. :)

________________________________

**Comment by the-dansan** [comment]
I must be dense; I don't find that button. I see it on my forked repo, but the wiki doesn't come with the fork.

I've attached the two edited files here, instead. Sorry for the effort for such a small change; if you knew the amount of time I spent trying to make Insight do something it wasn't supposed to do, though, you'd understand :)

Dan.

[Record-Readers.txt](https://github.com/jonwagner/Insight.Database/files/1607872/Record-Readers.txt)
[Specifying-Result-Structures.txt](https://github.com/jonwagner/Insight.Database/files/1607873/Specifying-Result-Structures.txt)

**Comment by jonwagner** [comment]
No worries. I'll upload the changes.
________________________________

**Comment by Jaxelr** [comment]
I had some time in my hands, so i uploaded the documentation changes as included here.
 Thanks a lot @the-dansan ! For further references you can find the edit pages on the wiki's upper right corner, Here's a sample url that takes you there:

Specifying Result Structures: https://github.com/jonwagner/Insight.Database/wiki/Specifying-Result-Structures/_edit
Record-Readers: https://github.com/jonwagner/Insight.Database/wiki/Record-Readers/_edit

**Comment by the-dansan** [comment]
Thank you Jaxelr. I must be special:

![image](https://user-images.githubusercontent.com/18700228/34642083-8c59d42e-f2db-11e7-85d7-883071cc915a.png)
