### ISSUE TITLE
parent/child self referencing

### ISSUE THREAD

**Issue by abbottmw** [jonwagner/Insight.Database#345]
I have been looking around, but I am trying to find how to handle a self referencing table  ( Example: ID,  ParentID)

My class looks like so

`public Class Foo
{
 public int ID {get;set;}
 public int ParentID {get; set;}
  pubic Foo Parent {get; set;}
}
`
I have found the one to one and one to many mappings, so im in the right place I feel, but Im not quite there yet.

**Comment by jonwagner** [comment]
Wow, wouldn't that be awesome if it magically worked?

Let me think about this one...

**Comment by abbottmw** [comment]
For now I just removed the Parent object and Im going by the ParentID.

**Comment by jonwagner** [comment]
We would have to do the processing after all of the records are read. I have a feeling that we can create an extension method on `ListReader` that lets you define the self-reference.

It would look something like:

    ...,
    Query.Returns<Parent>().SelfReferencing(p => p.ID, (parent, child) => child.Parent = parent)

We would use existing logic to try to automatically detect the ID field and the parent field, and then it would likely end up as:

    Query.Returns<Parent>().SelfReferencing()

**Comment by jonwagner** [comment]
Something like this is in v.6.1.3. It only works on the top-level recordset for now, but it should handle the most common use cases.

    [TestFixture]
    public class SelfReferencingTests : BaseTest
    {
        public class SelfReferencing
        {
            public int ID;
            public int ParentID;
            public SelfReferencing Parent;
        }

        [Test]
        public void SelfReferencingClassShouldAssignWithManualFunctions()
        {
            var results = Connection().QuerySql("SELECT ID=2, ParentID=1 UNION SELECT ID=1, ParentID=NULL",
                    null,
                    Query.Returns(Some<SelfReferencing>.Records)
                         .SelfReferencing(id: r => r.ID, parentId: r => r.ParentID, into: (c, p) => c.Parent = p)
                    );

            SelfReferencing parent = results.First(s => s.ID == 1);
            SelfReferencing child = results.First(s => s.ID == 2);

            Assert.AreEqual(parent, child.Parent);
        }

        [Test]
        public void SelfReferencingClassShouldAssignWithAutomaticFunctions()
        {
            var results = Connection().QuerySql("SELECT ID=2, ParentID=1 UNION SELECT ID=1, ParentID=NULL",
                    null,
                    Query.Returns(Some<SelfReferencing>.Records)
                         .SelfReferencing()
                    );

            SelfReferencing parent = results.First(s => s.ID == 1);
            SelfReferencing child = results.First(s => s.ID == 2);

            Assert.AreEqual(parent, child.Parent);
        }
    }
