### ISSUE TITLE
Oracle Provider (ODP.Net) Incompatible with latest version of Insight

### ISSUE THREAD

**Issue by tv14** [jonwagner/Insight.Database#346]
In order to fix Issue #343, we were required to update all our projects to Insight Database 6.1.2. Due to this update, we are now having problems with the Oracle Provider. 

Previously, we were using the Oracle Provider(ODP.net) because it allows us to BulkCopy.  However, the latest version of Oracle Provider is 5.2.10 and does not seem to be compatible with the newest version of Insight. When we try to register the Oracle Provider, there is a Argument Error.

Error:
https://imgur.com/a/9iTtH

**Comment by jonwagner** [comment]
Unfortunately, Oracle doesn't care about its customers enough to keep their drivers up to date and make them fully functional. We had plenty of trouble installing the Oracle binary drivers, so Insight 6.x only supports drivers that can be installed from NuGet.

Hopefully, Oracle actually gets around to releasing their new .NET core drivers sometime soon, and hopefully it also supports bulk copy.

https://twitter.com/OracleDOTNET/status/955487498922164224

The other option is to backport the fix to 5.2.11. It should be possible to port the fix by itself. I'll try to find some time later this week to do a build.

**Comment by tv14** [comment]
By backport fix, do you mean that you'll put the fix in the latest version of 5.2.11? Therefore, the NuGet version of 5.2.11 will contain the fix?

**Comment by jonwagner** [comment]
Yes, it should be possible to do a new 5.x build with the fix in it.

**Comment by jonwagner** [comment]
Unfortunately, I am no longer able to build v5.x builds due to all of the unmanaged drivers that 5.x supported. In order to do a 5.x build, I'd have to set up a new OS and install all of the drivers, and I can't afford the downtime for that. That's the main reason we dropped support for some drivers in 6.x.

I'm going to look into using Oracle's array binding feature for implementing bulk copy. It's probably not as efficient as streaming the data directly, but it should support batching.

**Comment by tv14** [comment]
That's sad to hear. Is there a way to work around this issue? Could we be able to create an extension that would add the fix that you did?

**Comment by jonwagner** [comment]
If you want to try a 5.x build, you would need to merge the following commits to the 5.0 branch:

Something like:

    git checkout 5.0
    git cherry-pick 69e4c98c37
    git cherry-pick 7f783ab37c
    .\build package

There is a good chance that there would be merge conflicts, but if it's an issue for you, it may be worth the effort.

**Comment by jonwagner** [comment]
NOTE: Oracle just released a beta of Oracle.OracleManaged.Core, and it doesn't look like they added bulk copy support.
