### ISSUE TITLE
Support (or switch to) MySqlConnector

### ISSUE THREAD

**Issue by bgrainger** [jonwagner/Insight.Database#347]
I'm the author of https://github.com/mysql-net/MySqlConnector, an OSS replacement for Oracle's Connector/NET.

Not only are we [more responsive at fixing outstanding bugs](https://mysql-net.github.io/MySqlConnector/tutorials/migrating-from-connector-net/#fixed-bugs), the MySqlConnector library is higher-performance and supports true async I/O (for `ExecuteNonQueryAsync`, `ExecuteReaderAsync`, etc.); we've also supported .NET Standard/.NET Core for much longer.

Are you interesting in either creating a separate project (`Insight.Database.Providers.MySqlConnector`) for clients who want to use a different underlying ADO.NET library, or simply changing `Insight.Database.Providers.MySql` to use `MySqlConnector` (so that async queries "just work")? (The API is almost exactly the same, so it should be a very simple change.) I'd be happy to submit a PR for either approach.

**Comment by jonwagner** [comment]
Hi Bradley!

I think it would be great to add support for MySqlConnector. We should create a new provider.

The easiest way to do that is to duplicate the code for the existing provider and change all of the references. If you have time to do that, I'll gladly accept a PR. If you don't have time, I can stick it in my work queue.

**Comment by jonwagner** [comment]
This will be in the 6.1.3 version to be posted later today.

Thanks for the help!
