### ISSUE TITLE
SQL Provider with CommandType Text always uses NVarChar

### ISSUE THREAD

**Issue by ghost1face** [jonwagner/Insight.Database#350]
Just as stated above, I know it's not possible to infer the proper parameter type when using CommandType.Text and only with StoredProcedures.  I've forked this repo and created a Mapper `IParameterDataTypeMapper` that can override the DbType that will be set on the DbParameter to ensure based on Mapping that a VarChar field is treated as such.

This will could improve database performance where implicit conversion will not need to happen due to data type mismatch.

Here's the [commit](https://github.com/ghost1face/Insight.Database/commit/0fa7da21a8a11f48cbc31fccbca36b26ec586db8) I performed on my fork but open to merging or making any changes if needed 

Let me know what you think, or if you think there may be a better approach!

**Comment by jonwagner** [comment]
I wonder if it's worth leaving the values as their native types (other than special things like lists and xml), rather than converting to varchar.

Do you have specific cases that you're trying to optimize?

**Comment by ghost1face** [comment]
In an application we have a lot of varchar fields.  One query in particular is querying on a CODE field but using Insight causes the query to look something like 

`EXEC 'SELECT * FROM dbo.Table WHERE Code=@code', N'@code=nvarchar(13)', @code=N'MY_CODE'`

This is default behavior from Insight when using inline text, but I did compare to:

`EXEC 'SELECT * FROM dbo.Table WHERE Code=@code', N'@code=varchar(13)', @code=N'MY_CODE'`

And notice lower reads compared to the `nvarchar` version.  Also, the `varchar` version does not show the warning regarding implicit conversion [CONVERT_IMPLICIT](https://www.scarydba.com/2016/05/03/implicit-conversion-performance/).

Unfortunately for me, the application I am working with has all inline sql so this problem starts to grow on a massive scale.  I didn't want to introduce a breaking change, so this is why I introduced another mapping interface to potentially alter the type (not much of a hit since it happens for the first time the statement is prepared and IL is compiled).

[Here, in my unit test](https://github.com/ghost1face/Insight.Database/blob/0fa7da21a8a11f48cbc31fccbca36b26ec586db8/Insight.Tests/ParameterDataTypeMapperTests.cs) I demonstrate this in the case of parameter `@mystyle` wanting to change it to DbType.AnsiString/Varchar.  This adds the flexibility to control inline queries but maintain the built in features of using a stored procedure.  Let me know if this helps.

**Comment by jonwagner** [comment]
Ah yes, and unfortunately, all .net strings are unicode, so there's no way to tell them apart.

Looking in your branch, there seem to be a lot of whitespace changes that make it difficult for me to parse through actual changes. Can you do an update without the whitespace changes?

**Comment by ghost1face** [comment]
Definitely, I can also add an .editorconfig file as well if you'd like to enforce whitespace rules.

**Comment by ghost1face** [comment]
#351 addresses and updates spacing as well

**Comment by jonwagner** [comment]
#351 is merged into master and will be in v6.2
