### ISSUE TITLE
Can't get One-To-Many example working with MySQL

### ISSUE THREAD

**Issue by aknoerig** [jonwagner/Insight.Database#353]
As far as I understand, for this I need to feed the reader the result of two select statements. It seems to me that MySQL always only returns one set, no matter how many selects I put into the procedure. This way, the reader always throws an `IndexOutOfRangeException` when trying to execute `ThenChildren()`.
Is there a way to make this work with MySQL?

**Comment by aknoerig** [comment]
Indeed, the same code works fine after switching to SqlServer. Officially, MySQL supports multiple result sets, but somehow it looks like Insight cannot pick them up.

**Comment by aknoerig** [comment]
Similarly, Identity Inserts do not seem to work with MySQL. Here, one would need to make use of a separate `SELECT LAST_INSERT_ID()` call, which again doesn't get handled by InsightDb. So the returned ID is always 0.

**Comment by jonwagner** [comment]
I'm not an expert on MySql, so I can't answer this off the top of my head. Can you create a set of test cases that illustrate these issues? Then I can just debug the test cases.

**Comment by aknoerig** [comment]
I have now uninstalled and replaced MySql with SqlServer, so I can't provide any test cases anymore.
But it should be possible to reproduce with the basic Beer/Glass examples as provided [in the Wiki](https://github.com/jonwagner/Insight.Database/wiki/Specifying-Result-Structures).

**Comment by jonwagner** [comment]
In that case, I'll try to fix some of the issues, but I won't be able to guarantee that I catch them all.

**Comment by aknoerig** [comment]
Thanks! In any case, if there are specific challenges to MySql, it would be helpful to mention them in the Wiki on the MySql connector page. Awesome work, by the way!

**Comment by jonwagner** [comment]
I added some test cases for MySql and there doesn't seem to be any issues with returning multiple recordsets or parent/child relationships.

Feel free to reopen if you have a repro case.
