### ISSUE TITLE
Question: Default value for mapping?

### ISSUE THREAD

**Issue by madrianr** [jonwagner/Insight.Database#355]
Hello,

is it possible to set a "Default" value for db.Query for the mapping?
I have to set a column to a value for all rows but cannot use the SQL for that...

robert

**Comment by jonwagner** [comment]
Can you provide more detail about what you are trying to do and what your restrictions are?

**Comment by madrianr** [comment]
I have solved that – you can delete the post

 

thank you

 

robert

 

Von: Jon Wagner [mailto:notifications@github.com] 
Gesendet: Freitag, 23. Februar 2018 15:08
An: jonwagner/Insight.Database
Cc: Robert Madrian (madrian e-dbsolutions); Author
Betreff: Re: [jonwagner/Insight.Database] Question: Default value for mapping? (#355)

 

Can you provide more detail about what you are trying to do and what your restrictions are?

**Comment by jonwagner** [comment]
Sure thing. For future reference, if you solve your own issue, it's polite to close the issue yourself so the maintainers don't spend time researching your question.

**Comment by madrianr** [comment]
OK – I’m sorry – found a solution at today – next time I will close it for myself…

 

robert

 

Von: Jon Wagner [mailto:notifications@github.com] 
Gesendet: Freitag, 23. Februar 2018 15:30
An: jonwagner/Insight.Database
Cc: Robert Madrian (madrian e-dbsolutions); Author
Betreff: Re: [jonwagner/Insight.Database] Question: Default value for mapping? (#355)

 

Sure thing. For future reference, if you solve your own issue, it's polite to close the issue yourself so the maintainers don't spend time researching your question.
