### ISSUE TITLE
Why does Insight depend on System.Data packages for .NET Framework?

### ISSUE THREAD

**Issue by sharpjs** [jonwagner/Insight.Database#363]
## Type
Question

## Current Behavior
Installing **Insight.Database** on a .NET Framework 4.7.1 project using a traditional `packages.config` file causes **System.Data.Common** and **System.Data.SqlClient** packages to be installed as dependencies.

## Expected behavior
**Insight.Database** references the **System.Data** assemblies shipped with the .NET Framework.

## Steps to Reproduce
Install Insight in a .NET Framework 4.7.1 project using a `packages.config` file.

### Any other comment
This is confusing.  As I understand it, those packages are for .NET Core/Standard.  I don't know why those packages exist for .NET Framework, since the framework ships those assemblies already.  Which ones are the latest version?

* System.Data.Common.dll, AssemblyVersion 4.0.0.0, FileVersion 4.7.2558.0, shipped with .NET 4.7.1
* System.Data.Common.dll, AssemblyVersion 4.1.0.0, FileVersion 1.0.24212.1, in its package's net451 folder?

Ultimately, I need to know how I should reconcile Insight's dependencies with other packages that depend on the Framework's **System.Data** assemblies.  Which System.Data.Foo wins?  Do I need binding redirects?

**Comment by jonwagner** [comment]
Insight requires Common and SqlClient in order to connect to the database. For each target platform, we specify the minimum version that is required to support Insight's functionality. The .NET platform is supposed to resolve this automatically.

Is there a specific problem that you are trying to address?

**Comment by jonwagner** [comment]
Those are good questions! I don't have all of the answers, so let me do some digging.

Generally, newer assemblies should be backward-compatible, but that's not always the case. We also want to make sure that assembly dependencies don't leak to other projects unintentionally.

**Comment by andymac4182** [comment]
I think this will be related to this reference. 
https://github.com/jonwagner/Insight.Database/blob/f0cea5332e7443992f2c7ebfa3bf638e4ae1b426/Insight.Database.Providers.Default/Insight.Database.Providers.Default.csproj#L17 
It probably would need to be wrapped similar to https://github.com/jonwagner/Insight.Database/blob/f0cea5332e7443992f2c7ebfa3bf638e4ae1b426/Insight.Database.Core/Insight.Database.Core.csproj#L20 so that it uses the reference to the built in version for full framework and the nuget reference for netcore. Personally I think this is ok since more and more packages are dropping a default reference to full framework and just targeting netstandard which using the nuget is the only way to use these references.

**Comment by sharpjs** [comment]
Here's what I see in ILSpy looking at a DLL from the NuGet package.  It just forwards all types to the underlying .NET Framework DLL.

![screen shot 2018-04-20 at 11 50 04 am](https://user-images.githubusercontent.com/708461/39075420-6183040c-44aa-11e8-9364-721a62010e49.png)

So, in one sense, these seem harmless in that the various dependents are going to get the .NET Framework 4.7.1 System.Data.dll implementations regardless.  On the other hand, it is confusing and easily avoided.  Similar to what @andymac4182 wrote, I've done it like this before:

```
<ItemGroup Condition="'$(TargetFramework)'=='netstandard1.5'">
  <PackageReference Include="System.Data.SqlClient" Version="$(SqlClientVersion)" Condition="$(SqlClientVersion) != ''" /> 
</ItemGroup>
```

I don't know if it matters, but I've always seen quotes around the left-hand side in the `Condition` attributes.

**Comment by jonwagner** [comment]
Should be easy to fix then

On Apr 20, 2018, at 5:59 PM, Jeff Sharp <notifications@github.com<mailto:notifications@github.com>> wrote:


Here's what I see in ILSpy looking at a DLL from the NuGet package. It just forwards all types to the underlying .NET Framework DLL.

[screen shot 2018-04-20 at 11 50 04 am]<https://user-images.githubusercontent.com/708461/39075420-6183040c-44aa-11e8-9364-721a62010e49.png>

So, in one sense, these seem harmless in that the various dependents are going to get the .NET Framework 4.7.1 System.Data.dll implementations regardless. On the other hand, it is confusing and easily avoided. Similar to what @andymac4182<https://github.com/andymac4182> wrote, I've done it like this before:

<ItemGroup Condition="'$(TargetFramework)'=='netstandard1.5'">
  <PackageReference Include="System.Data.SqlClient" Version="$(SqlClientVersion)" Condition="$(SqlClientVersion) != ''" />
</ItemGroup>


I don't know if it matters, but I've always seen quotes around the left-hand side in the Condition attributes.

**Comment by jonwagner** [comment]
I removed the explicit dependencies from .net framework builds in v6.2.1. Let me know if you still have an issue.

**Comment by sharpjs** [comment]
Thanks, @jonwagner.  Just tried it, and the Insight.Database.Configuration project still depends on one, specifically in the `net451` build.
<img width="278" alt="screen shot 2018-05-13 at 4 34 29 pm" src="https://user-images.githubusercontent.com/708461/39972852-c064bbf4-56cb-11e8-81b4-199971b2444f.png">

**Comment by jonwagner** [comment]
v6.2.2. has the config project fixed as well.

**Comment by sharpjs** [comment]
Hey @jonwagner , 6.2.2 still has the dependency.  Here's what I see in NuGet.org:

![screen shot 2018-05-25 at 3 34 11 pm](https://user-images.githubusercontent.com/708461/40568721-3916736c-6031-11e8-9647-6a951d74cc4c.png)

**Comment by Jaxelr** [comment]
Could you check your cache? It looks correctly at least on my end.

Heres the nuget page:

![image](https://user-images.githubusercontent.com/5913008/40576227-2eaadb22-60c0-11e8-92a2-9f450a3992f2.png)

And heres the Nuget window on VS 2017:

![image](https://user-images.githubusercontent.com/5913008/40576228-40985dbe-60c0-11e8-99d6-47fef82aa334.png)

**Comment by jonwagner** [comment]
Sorry that was a merge error on my part :(

**Comment by jonwagner** [comment]
Alrighty...v6.2.3 no longer has a library dependency when targeting .NET Framework.

I checked Core, Configuration, Providers.Default, and Json packages. Let me know if you find any more.

**Comment by sharpjs** [comment]
Thanks!  Looks good here.
