### ISSUE TITLE
Not passing paramater value with @> PostgreSQL operator

### ISSUE THREAD

**Issue by michael-wolfenden** [jonwagner/Insight.Database#376]
## Type
What kind of issue is this?

```
[X] Bug report.
[ ] Feature request.
```

Given the following 

```sql
CREATE TABLE books (  
  book_id serial NOT NULL,
  data jsonb
);

INSERT INTO books VALUES (1, '{"title": "Sleeping Beauties"}');
```

I can use the `@>` operator to query books based on `title`

```sql
SELECT data->'title' FROM books WHERE data @> '{ "title": "Sleeping Beauties" }';
```

When reproducing this query using `Insights`

```csharp
NpgsqlLogManager.Provider = new ConsoleLoggingProvider(minLevel: NpgsqlLogLevel.Debug);
NpgsqlLogManager.IsParameterLoggingEnabled = true;

PostgreSQLInsightDbProvider.RegisterProvider();

using (var connection = new NpgsqlConnection("....."))
{
    connection.Open();
    connection.QuerySql<string>(
        "SELECT data->'title' FROM books WHERE data @> '{ \"title\": \"@title\" }';",
        new { title = "Sleeping Beauties" }
    )
}
```
It returns zero results as it doesn't appear to substitute the `@title` variable. The `NpgsqlLogManager` output is:

```
Executing statement(s):
  SELECT data->'title' FROM books WHERE data @> '{"title": "@title" }'
Parameters:
  $1: Sleeping Beauties
```

**Comment by jonwagner** [comment]
This seems to indicate that the parameter is making it to postgres

```
Executing statement(s):
  SELECT data->'title' FROM books WHERE data @> '{"title": "@title" }'
Parameters:
  $1: Sleeping Beauties
```

Postgres is probably ignoring it because you have `"@title"` in quotes. Remove the quotes and it should treat it as a parameter.

**Comment by jonwagner** [comment]
This post seems to show a different way to do it:

https://stackoverflow.com/questions/29484271/postgres-sending-parameter-to-jsonb-field-in-a-function

Have you tried:

`SELECT data->'title' FROM books WHERE data->title @> @title;`

Or something like that.

**Comment by michael-wolfenden** [comment]
That doesn't work either 

```
Connection opened
Executing statement(s):
  SELECT data->'title' FROM books WHERE data->'title' @> $1
Parameters:
  $1: Sleeping Beauties

PostgresException - 42883: operator does not exist: jsonb @> text 
```

Which makes sense as the `@>` is the contains operator and its trying to check whether the jsonb title on the left (`data->'title'`) contains the text on the right `@title`.

The only way I can this query working is to define the entire json object as a parameter

```csharp
connection.QuerySql<string>(
    "SELECT data->'title' FROM books WHERE data @> @data::jsonb",
    new { data = "{ \"title\": \"Sleeping Beauties\" }" }
)
```

**Comment by jonwagner** [comment]
I think we figured this one out. Feel free to reopen if it doesn't work for you.
