### ISSUE TITLE
SQL Injection question on below Implementation 

### ISSUE THREAD

**Issue by keerthiraja1988** [jonwagner/Insight.Database#392]
**Question**

Will below implementations cause SQL Injection issues. Can you please advice on using inline queries and passing parameters **_"SELECT * FROM Beer WHERE type = @type"._** 

Are both implementations are safe to use?

## Steps to reproduce

**Implementation 1**
```

public interface IBeerRepository
{	
	[Sql("SELECT * FROM Beer WHERE type = @type")]
	IList<Beer> GetBeerByType(string type);
}
```

**Implementation 2**

```
IList<Beer> beer = Database.Connection().QuerySql<Beer>(
	"SELECT * FROM Beer WHERE Name = @Name",
	new { Name = "IPA" });
```

- Dotnet version: [netcore2,]
- Database: [SQL Server]
- Library version: [6.2.3]

**Comment by jonwagner** [comment]
Insight will create parameters for anything that you `@param`, regardless of whether you use an interface or directly use the connections.

________________________________
