### ISSUE TITLE
Insert entity with relation (one to one)

### ISSUE THREAD

**Issue by falvarador** [jonwagner/Insight.Database#394]
I  am  currently trying to insert a "Person entity" that has relations (one to one) and collections (one to many) associated. My idea is to be able to insert in a unique SP the "Person entity", its realtions and its collections, to do that I tried the insert method by using type as table as it is detailed in Insight.Database Wiki. It works fine for collections, but, I am missing a method able to do the same but considering relations (one to one). 

Is currently there a way to do that, or is it possible to add this function (insert relation one to one)?

**Comment by jonwagner** [comment]
If you add the related fields to the TVP, insight should automatically pick them up on the sub-object if they are named uniquely.

On Mar 22, 2019, at 12:52 AM, Freddy Alvarado R <notifications@github.com<mailto:notifications@github.com>> wrote:


I am currently trying to insert a "Person entity" that has relations (one to one) and collections (one to many) associated. My idea is to be able to insert in a unique SP the "Person entity", its realtions and its collections, to do that I tried the insert method by using type as table as it is detailed in Insight.Database Wiki. It works fine for collections, but, I am missing a method able to do the same but considering relations (one to one).

Is currently there a way to do that, or is it possible to add this function (insert relation one to one)?
