### ISSUE TITLE
Auto Interface stored proc output parameter not returning?

### ISSUE THREAD

**Issue by ThisNoName** [jonwagner/Insight.Database#399]
I have this simple proc
```
ALTER PROCEDURE InsightTest @Id int, @Affected int = 0 OUTPUT
AS 
SET @Affected = @Id + 1
```
running in SQL works
```
DECLARE @affected int
EXEC InsightTest @Id = 123, @Affected = @affected OUTPUT 
PRINT @affected -- 124
```

Here's the test interface
```
    public interface IDbInsight
    {
        [Sql("InsightTest @id=@id, @affected=@affected OUTPUT")]
        void MsgTest(int id, out int affected);
    }
```
It turns into this SQL
```
exec sp_executesql N'InsightTest @id, @affected OUTPUT',
    N'@id int,@affected int',@id=123,@affected=0
```

But the output parameter does not return to interface, nor does it work in SQL
```
DECLARE @affected INT = 0;
exec sp_executesql N'InsightTest @id, @affected OUTPUT',
    N'@id int,@affected int',@id=123,@affected=0
PRINT @affected -- 0
```

Did I miss something important?  Thanks

**Comment by jonwagner** [comment]
Insight can’t bind output parameters to text-based sql queries. That’s what you’re doing with the Sql attribute.

I would expect this to work:

    public interface IDbInsight
    { void InsightTest(int id, out int affected);
    }

On Jul 23, 2019, at 2:19 PM, ThisNoName <notifications@github.com<mailto:notifications@github.com>> wrote:


I have this simple proc

ALTER PROCEDURE InsightTest @Id int, @Affected int = 0 OUTPUT
AS
SET @Affected = @Id + 1


running in SQL works

DECLARE @affected int
EXEC InsightTest @Id = 123, @Affected = @affected OUTPUT
PRINT @affected -- 124


Here's the test interface

    public interface IDbInsight
    {
        [Sql("InsightTest @id=@id, @affected=@affected OUTPUT")]
        void MsgTest(int id, out int affected);
    }


It turns into this SQL

exec sp_executesql N'InsightTest @id, @affected OUTPUT',
    N'@id int,@affected int',@id=123,@affected=0


But the output parameter does not return to interface, nor does it work in SQL

DECLARE @affected INT = 0;
exec sp_executesql N'InsightTest @id, @affected OUTPUT',
    N'@id int,@affected int',@id=123,@affected=0
PRINT @affected -- 0


Did I miss something important? Thanks

**Comment by ThisNoName** [comment]
Thanks for the quick follow up.  It does work, but almost like it was faking it  ^_^  I'll dig around to see where the real magic happens.  
```
declare @p2 int
set @p2=124
exec InsightTest @Id=123,@Affected=@p2 output
select @p2
```
On the other hand, it would be nice having an option to shield proc name and parameter from the rest, even when auto mapped.  Some vendor systems have really ugly and cryptic proc and parameter names, can't imagine exposing all that as service endpoints.

**Comment by jonwagner** [comment]
I believe that if you just use the SqlAttribute with just the procedure name, it will detect it as a stored proc. If that doesn't work, you can also add CommandType=StoredProc

e.g.

[Sql("ProcName")] void DifferentProc(...);
[Sql("ProcName", CommandType=CommandType.StoredProcedure)]

as for parameters, I believe that the ColumnAttribute can be used to remap the names if you don't want the names to match.

void Proc ([Column("ParameterName")] int canHaveDifferentName);

________________________________

**Comment by ThisNoName** [comment]
Make StoredProcedure Cool Again!!!
