### ISSUE TITLE
Using storage type of tinyint for enums does not work

### ISSUE THREAD

**Issue by jbright** [jonwagner/Insight.Database#4]
In some cases, I'd like to use a tinyint for my table because it's an enum value and I know I'll never need more than 256 values. If I do that, I get casting issues on deserialization.

[InvalidCastException: Specified cast is not valid.]
   Deserialize-Bit.Services.Templates.TemplateAttribute-6b6001d8-a759-4877-963a-ae30a1aba731(IDataReader ) +902

[DataException: Error parsing column 4 (AttributeType=1 - Byte)]
   Deserialize-Bit.Services.Templates.TemplateAttribute-6b6001d8-a759-4877-963a-ae30a1aba731(IDataReader ) +1059
   Insight.Database.<AsEnumerable>d__13`1.MoveNext() in c:\projects.net\Insight\Insight.Database\Insight.Database\DbReaderExtensions.cs:443
   System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) +536
   System.Linq.Enumerable.ToList(IEnumerable`1 source) +80
   Insight.Database.DBReaderExtensions.ToList(IDataReader reader) in c:\projects.net\Insight\Insight.Database\Insight.Database\DbReaderExtensions.cs:36
   Insight.Database.<>c__DisplayClass13`1.<Query>b__12(IDbConnection c) in c:\projects.net\Insight\Insight.Database\Insight.Database\DbConnectionExtensions.cs:372

**Comment by jonwagner** [comment]
This was a breaking change by the npgsql team. In v4.0, npgsql no longer supports putting enums directly in sql parameters. You have to cast them to an integral time.

I've added code to compensate for this.

This will be fixed in v6.2.5 to be released next week.

**Comment by jonwagner** [comment]
6.2.5 is now available
