### ISSUE TITLE
Dynamically Added Properties Causes Exception On Execute

### ISSUE THREAD

**Issue by radleta** [jonwagner/Insight.Database#404]
# Describe the bug

The goal is to be able to pull objects out of the DB via a stored procedure. Modify the result by adding additional columns to the data dynamically. Finally, passing the modified objects back to another stored procedure.

The reason this behavior is needed to support a dynamic system that allows reading inputs with a mix of well-known data and dynamic data then writing all the data back to the database via a table type procedure.

When attempting the final save back to the database an exception occurs referring to the fact that the data was not mapped back to the inputs. This is evident due to the NOT NULL requirement on the input table type. (Note: I removed the NOT NULL and ended up with all the data only having NULLs as if nothing was assigned.)

Exception from the example attached.

```
System.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=Cannot insert the value NULL into column 'InputString', table '@Input'; column does not allow nulls. INSERT fails.
The data for table-valued parameter "@Input" doesn't conform to the table type of the parameter. SQL Server error is: 515, state: 2
The statement has been terminated.
  Source=Core .Net SqlClient Data Provider
  StackTrace:
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Insight.Database.DBConnectionExtensions.<>c__DisplayClass164_0.<Execute>b__1(IDbCommand _, IDataReader __)
   at Insight.Database.DBConnectionExtensions.ExecuteAndAutoClose[T](IDbConnection connection, Func`2 getCommand, Func`3 translate, CommandBehavior commandBehavior)
   at Insight.Database.DBConnectionExtensions.Execute(IDbConnection connection, String sql, Object parameters, CommandType commandType, Boolean closeConnection, Nullable`1 commandTimeout, IDbTransaction transaction, Object outputParameters)
   at InsightDatabaseDynamicInputOutputExample.Program.Main(String[] args) in C:\Dev\git\InsightDatabaseDynamicInputOutputExample\InsightDatabaseDynamicInputOutputExample\Program.cs:line 89
```

## Steps to reproduce

See 
[InsightDatabaseDynamicInputOutputExample.zip](https://github.com/jonwagner/Insight.Database/files/3560512/InsightDatabaseDynamicInputOutputExample.zip)
attached for the complete project.

Excerpt from the example:

T-SQL
```
CREATE PROCEDURE dbo.sp_get_InsightDatabaseExample1
AS
BEGIN
    SELECT 'StringValue' InputString,
        GETDATE() InputDate;
END;
GO;

--- snip

CREATE TYPE dbo.InsightDatabaseExample1InputType AS TABLE (
    InputString VARCHAR(50) NOT NULL,
    InputDate DATETIME NOT NULL,
    OutputValue INT NOT NULL
);
GO;

CREATE PROCEDURE dbo.sp_write_InsightDatabaseExample1(
    @Input dbo.InsightDatabaseExample1InputType READONLY
)
AS
BEGIN
    
    SET NOCOUNT ON;

    -- do something with the data

    RETURN 0;

END;
```

C#
```
// call the read procedure
var rows = new SqlConnection(ConnectionString).Query(sql: "dbo.sp_get_InsightDatabaseExample1");

// modify the results by using then adding data
foreach (var row in rows)
{
    row.TryAdd("OutputValue", 1);
}

// call the write procedure
new SqlConnection(ConnectionString).Execute(sql: "dbo.sp_write_InsightDatabaseExample1", parameters: new { Input = rows });
```

## Expected behavior

The expectation is that the `Execute` call at the end would properly map the data to the TABLE TYPE and no exception would occur.

- Dotnet version: netcoreapp2.1
- Database: Microsoft SQL Server 2016 (SP2-CU7) (KB4495256) - 13.0.5337.0 (X64)   May 16 2019 02:24:21   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor)
- Library version: [6.2.9]

**Comment by rkramer1964** [comment]
Does the TryAdd succeed?

**Comment by rkramer1964** [comment]
DBParameterGenerator.cs - dynamic parameters don't seem to check to for enumerable nor table valued parameters like the class generator does.

**Comment by radleta** [comment]
@rkramer1964 Yes, the `TryAdd` succeeds. I've inspected the `row` and all three pairs exist in the `FastExpando`.

**Comment by jonwagner** [comment]
rkramer1964 is correct.

Dynamic calls do not support TVPs.

Dynamic calls were intended to be convenience methods for one-off calls to the database, and we did not invest in advanced features such as TVPs and enumerated parameters. We are not likely to add these features to the dynamic scenario.

If you're going to take the time to have your database accept structured data, you might as well add a small data-only class to your .net/c# code.

Explanation:

* Dynamic objects do not have a class/type that Insight can use for caching parameter types.
* When you make a dynamic call, Insight will use `PrepareStatement` or the equivalent to get the types of parameters. This is not cached.
* For TVPs, Insight would need to go back to the database to acquire the table signature, then build the type mapping to get data into it.

**Comment by radleta** [comment]
@jonwagner Any recommendations on a framework that would provide this functionality?

**Comment by jonwagner** [comment]
As far as I know, Insight is the only ORM that really supports TVPs.

Options:

A) use a data transfer object / class instead of a dynamic object
B) use an anonymous type (insight gets typeinfo for these). It will still feel dynamic and allow you to have types specific to each query.

E.g:

.query(“proc”, rows.Select(r => new { inputstring=r.inputstring }))

On Sep 2, 2019, at 11:41 PM, Richard Adleta <notifications@github.com<mailto:notifications@github.com>> wrote:


@jonwagner<https://github.com/jonwagner> Any recommendations on a framework that would provide this functionality?

**Comment by radleta** [comment]
@jonwagner Thanks for the insight.

Your B option seems closes to accomplishing what I want to do. The issue is that what I'm trying to do is dynamic at runtime so the anonymous type cannot be created via the new {} syntax.

I found a really old article on how to accomplish creating anonymous types at runtime [here](https://benohead.com/create-anonymous-types-at-runtime-in-c-sharp/). It appears I could create and cache the dynamic types for each procedure. Seems a little inefficient since I'd ultimately be using reflection to get/set the properties after the type is created. It does seem to solve my dynamic problem and allows Insight.Database to know what I'm trying to do on the output.

I know I'm working on the edge case here so just brainstorming solutions. I'd hate to go off an build a ton a code when the solution is already there.

Another thought I had is to take various pieces from Insight.Database to accomplish the goal. If Insight.Database is already reading the anonymous type information when I call Execute on the stored procedure, I'd just have to tweak it to get that information from a different object rather than the reflected type information from the anonymous type. The origin of this type information would be gathered from the origin stored procedure's output then appended and passed back to the output stored procedure. This seems the least painful of the options considered so far that fit the dynamic nature of what I'm trying to accomplish.

**Comment by radleta** [comment]
I sharing this should anyone find this issue and want to figure out how to do what I was trying to do with Insight.Database.

I created a [working example](https://github.com/radleta/Insight.Database/commit/331de3280b99f7cc61ef4c023199dcd94785a663) of what I was referring to above in a [branch of my fork](https://github.com/radleta/Insight.Database/tree/user-radleta-dynamic-in-out-example-v1).

The example is not optimized completely for every case. It does show how to accomplish it with a working example that can be pulled and run.

One optimization that could be improved upon with this v1 version is to create via runtime IL a wrapper class around the FastExpando who's property accessors reference the underlying FastExpando. This would save the need to duplicating the underlying data of the FastExpando to another type.

There are some notes added on minor suggestions for optimization.

**Comment by radleta** [comment]
I implemented the optimization above by creating a dynamic wrapper [version](https://github.com/radleta/Insight.Database/commit/b4bb4bc33bd66207a6af431fe4d792935f594de7) in a [separate branch](https://github.com/radleta/Insight.Database/tree/user-radleta-dynamic-in-out-example-v2). It works and is slightly more optimized than v1.
