### ISSUE TITLE
database function

### ISSUE THREAD

**Issue by menorless** [jonwagner/Insight.Database#405]
Hello, Can I use auto-interface for executing sql functions, like this:

public interface IBeerRepository
{
	[Sql("fn_CountCustom")]
	void CountCustom(Beer beer);
}

or something like that.

**Comment by jonwagner** [comment]
I don't remember if that was ever implemented. 

You can try:

```
[Sql("fn_CountCustom", CommandType.SqlFunction)]
```

**Comment by menorless** [comment]
> I don't remember if that was ever implemented.
> 
> You can try:
> 
> ```
> [Sql("fn_CountCustom", CommandType.SqlFunction)]
> ```

thanks

**Comment by Jaxelr** [comment]
Is it SQL Server the DB? This would work:

``` c#
public interface IBeerRepository
{
   [Sql("SELECT dbo.fn_CountCustom()")]
   void CountCustom();
}
```

**Comment by menorless** [comment]
> I don't remember if that was ever implemented.
> 
> You can try:
> 
> ```
> [Sql("fn_CountCustom", CommandType.SqlFunction)]
> ```

this doesn't work, because CommandType.SqlFunction not exists.

**Comment by Jaxelr** [comment]
Closing, if you have any other issues with this snippet reopen issue.

Thanks.
