### ISSUE TITLE
Named result sets

### ISSUE THREAD

**Issue by S1r-Lanzelot** [jonwagner/Insight.Database#406]
# Describe the feature
It would be nice to name the result sets that are produced from a Query.

## Is this feature related to a problem, describe
The benefit of named result sets is a lot like named Tuples, it helps with readbility and accuracy. Set1, Set2, ... SetN is a bit opaque. 

## Additional context
I will look into contributing, just throwing up the feature request for discussion. Thanks for the library :100:

**Comment by jonwagner** [comment]
I looked into that when named tuples were created, but it's not possible.

.NET doesn't allow for names of properties to change. Named tuples are actually done at compile time with some attribute magic.

**Comment by S1r-Lanzelot** [comment]
Ah bummer, ok thanks for letting me know.
