### ISSUE TITLE
Question - .AsParallel<IDB2Repository> DB2 Connection string

### ISSUE THREAD

**Issue by keerthiraja1988** [jonwagner/Insight.Database#410]
Do I need to include **`Add Persist Security Info=true; & Integrated Security=true;`** in connection string for DB2 while using .AsParallel as given in 

_https://github.com/jonwagner/Insight.Database/wiki/Auto-Interface-Implementation#parallel-programming_
? 

```
string db2ConnectionString = "Driver={IBM DB2 ODBC DRIVER}; Hostname=db2connect; Port=500; Protocol=TCPIP;Database=DSNT; UID=********; PWD=******;Persist Security Info=true; Integrated Security=true;";

var _db2Connection = new System.Data.Odbc.OdbcConnection(db2ConnectionString);
IDB2Repository i = c.AsParallel<IDB2Repository>();
```

- Dotnet version: [dotnet472]
- Database: [DB2]
- Library version: [6.2.9]

**Comment by jonwagner** [comment]
I don’t think you need a different connection string for asparallel. Just use the one you normally connect with.

On Nov 6, 2019, at 6:05 AM, keerthiraja1988 <notifications@github.com> wrote:

﻿

Do I need to include Add Persist Security Info=true; & Integrated Security=true; in connection string for DB2 while using .AsParallel as given in

https://github.com/jonwagner/Insight.Database/wiki/Auto-Interface-Implementation#parallel-programming
?

string db2ConnectionString = "Driver={IBM DB2 ODBC DRIVER}; Hostname=db2connect; Port=500; Protocol=TCPIP;Persist Security Info=true; Integrated Security=true;";

var _db2Connection = new System.Data.Odbc.OdbcConnection(db2ConnectionString);
IDB2Repository i = c.AsParallel<IDB2Repository>();


  *   Dotnet version: [dotnet472]
  *   Database: [DB2]
  *   Library version: [6.2.9]

**Comment by keerthiraja1988** [comment]
Thank You for your reply.

I usually connect by registering the dependency in Autofac DI module and call the db in home controller in below manner, without Add Persist Security Info=true; & Integrated Security=true;

Is this approach correct? or it will cause this issues : When using password-based security, .NET will erase the password from your connection string when the connection is opened.  

**DB2DatabaseIOCModule.cs**
```
public class DB2DatabaseIOCModule : Module
	{
		private readonly System.Data.Odbc.OdbcConnection _db2Connection;
		
		public DB2DatabaseIOCModule()
		{
			OdbcInsightDbProvider.RegisterProvider();

			this._db2Connection = new System.Data.Odbc.OdbcConnection("Driver={IBM DB2 ODBC DRIVER}; Hostname=db2connect; Port=500; Protocol=TCPIP;Database=DSNT; UID=********; PWD=******;");			
		}

		protected override void Load(ContainerBuilder builder)
		{
			builder
			.Register(b => this._db2Connection.As<Interface1>())
			.InstancePerRequest();

			base.Load(builder);
		}
	}
```
	
**Global.asax.cs**
```
protected void Application_Start()
		{
			AreaRegistration.RegisterAllAreas();
			FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
			RouteConfig.RegisterRoutes(RouteTable.Routes);
			BundleConfig.RegisterBundles(BundleTable.Bundles);

			var builder = new ContainerBuilder();
			builder.RegisterModule(new DB2DatabaseIOCModule());

			builder.RegisterControllers(typeof(MvcApplication).Assembly);

			var container = builder.Build();

			// Set MVC DI resolver to use our Autofac container
			DependencyResolver.SetResolver(new AutofacDependencyResolver(container));
		}
```
		
**HomeController.cs** (I will be conencting SQL from BAL not from contoller, its just an example)
```
private readonly IDB2Repository _DB2Repository;
		
		public HomeController(IDB2Repository DB2Repository)
		{
			
			_DB2Repository = DB2Repository;
		}

public async Task<ActionResult> Index()
		{
			var result = await _DB2Repository.GetValue(2);
			return View();
		}
		

```

**Comment by jonwagner** [comment]
I think I understand. If you're using a DI container and your database provider wipes your credentials from connections, then I recommend creating the connection from your connection string each time.

```
public class DB2DatabaseIOCModule : Module
	{
		private readonly System.Data.Odbc.OdbcConnectionString _db2ConnectionString;
		
		public DB2DatabaseIOCModule()
		{
			OdbcInsightDbProvider.RegisterProvider();

			this. _db2ConnectionString = new System.Data.Odbc.OdbcConnectionString("Driver={IBM DB2 ODBC DRIVER}; Hostname=db2connect; Port=500; Protocol=TCPIP;Database=DSNT; UID=********; PWD=******;");			
		}

		protected override void Load(ContainerBuilder builder)
		{
			builder
			.Register(b => this._db2ConnectionString.OpenAs<Interface1>())
			.InstancePerRequest();

			base.Load(builder);
		}
	}
```
