### ISSUE TITLE
Before using Insight.Database, I have a few questions

### ISSUE THREAD

**Issue by MercedeX** [jonwagner/Insight.Database#413]
I want to use Insight.Database in a large cloud based system. I have a few questions though:

1. How stable it is for production system? Does it have any issues that might hamper its use in production environment?
2. Is it still actively maintained?
3. Is it extensible? for instance for NoSql databases like Cassandra and similar?
4. Is there any performance benchmark available for high write or high read environment?

**Comment by keerthiraja1988** [comment]
How stable it is for production system? Does it have any issues that might hamper its use in production environment? - I have used with MSSQL, DB2 and Oracle with than 6 projects. No issues I have faced.

Is there any performance benchmark available for high write or high read environment? Yes, Check this repo -> https://github.com/InfoTechBridge/OrmBenchmark , Insight seems fine in performance.

**Comment by Jaxelr** [comment]
1. This question is difficult to answer, considering what scenarios you would be using it for. 
       -  If you plan to have lots of customizable result sets, insight is highly practical and with a succint API. 
       - Plan on using BulkInserts? Insight supports them out of the box.
       - Async? Multiple Active Connections? Insight is flexible for those scenarios, you can even roll your own record reader.
2. Sure, as far as i know all collaborators have jobs and we dont get paid for OSS, so we are not available 24/7. 
3. No and i dont think it is considered on future plans. Managing NoSql databases is a whole other monster and i would not suggest doing so with a transactional ORM. But it does manage most SQL Providers.
4. The benchmarks on (OrmBenchmark)[https://github.com/InfoTechBridge/OrmBenchmark] could use an upgrade, so be on the lookout for a PR. I would also like to create a repo using [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet) which would give us a bit more perspective.

**Comment by jonwagner** [comment]
As for active maintenance, I might not be putting out same-day fixes anymore, but I do intend to keep producing new builds as issues arise and new features are requested.

**Comment by MercedeX** [comment]
thanks a lot. i have started giving it a try in a test app. I will try to post my results and findings or any questions if i may have.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by Jaxelr** [comment]
I have created a [Insight Benchmark](https://github.com/Jaxelr/Insight.Database.Benchmark) repo that could give you more information about the performance and allow you to thinker and evaluate what scenarios work for you in terms of performance. Closing this issue.
