### ISSUE TITLE
Informix database support

### ISSUE THREAD

**Issue by deokershesh** [jonwagner/Insight.Database#415]
Could you please support Informix database as well? And/Or provide steps to support any additional databases so that we can work to support Informix as well.

Thanks
-Shesh

**Comment by jonwagner** [comment]
The best way to support a new database is to copy one of the provider projects and implement the methods to wrap your the database connection, command, and parameters.

Take a look at the Postgres provider. It's pretty straightforward.

If you get it working, we could add it to the official repo if there is a docker image of Informix that  we can use for testing.

**Comment by juancgarciaco** [comment]
> Could you please support Informix database as well? And/Or provide steps to support any additional databases so that we can work to support Informix as well.
> 
> Thanks
> -Shesh

Hi deokershesh, Nice day.

I use DB2 Implementation to connect IDS 10.5, 11.2 And 14.x. If you need help, contact me.

**Comment by deokershesh** [comment]
@jonwagner, The docket image is available at https://hub.docker.com/r/ibmcom/informix-developer-database/ . Please free to explore the image, if you need any help/info please do let me know. We will work on supporting Informix and be in touch with you.
Thanks for quick response.

**Comment by deokershesh** [comment]
@juancgarciaco, Thanks for offering help, we will connect with you.

**Comment by rhtpandeyIN** [comment]
@juancgarciaco 
> I use DB2 Implementation to connect IDS 10.5, 11.2 And 14.x. If you need help, contact me.

Could you please send us the repo link or some sample application link so that we can follow that for our reference.

**Comment by juancgarciaco** [comment]
Sure, I'm Working on It! and I'll Upload solution soon

**Comment by juancgarciaco** [comment]
Hi, I publish a basic sample about connection, consume of views, SP only queryng data.
Later I will show you how to save data by direct insert or through an SP
For the rush just reach this piece.

https://github.com/juancgarciaco/insightdb.db2

To Everyone, have a nice day.

**Comment by rhtpandeyIN** [comment]
thanks @juancgarciaco for the sample repo. But can you please update the readme with the project's folder structure and code work flow details. I have never used insight database so it is quite hard for me to understand it for the first time. A brief and basic details would do help. Thanks again.

**Comment by jonwagner** [comment]
Since the DB2 driver works with Informix, I'm going to close this. Let me know if there are any Informix-specific issues.
