### ISSUE TITLE
Support SqlHierarchyId type for .NET Core

### ISSUE THREAD

**Issue by yegor-n-a** [jonwagner/Insight.Database#418]
To avoid repetitions, I'll keep it short:

1. [Description](https://github.com/dotnet/SqlClient/issues/322)
2. [Context](https://github.com/aspnet/EntityFrameworkCore/issues/365)
3. [Related issue](https://github.com/dotnet/SqlClient/issues/79)
4. [How to fix](https://linq2db.github.io/articles/FAQ.html#how-can-i-use-sql-server-spatial-types)
5. Example: [EF .Core implementaion](https://github.com/aljones/EFCore.SqlServer.HierarchyId)

Are there any plans to implement aforementioned?

Thanks.

**Comment by yegor-n-a** [comment]
@jonwagner Any commentaries on that?

**Comment by Jaxelr** [comment]
This seems to work for me (netcore):

```c#
void Main()
{
	var conn = new SqlConnection(MyExtensions.SQLConnectionString);
	SqlInsightDbProvider.RegisterProvider();

	var response = conn.QuerySql<Foo>("select 3 as [Id], hierarchyid::Parse('/1/2/3/') as [Path]");

        //Linqpad
	//response.Dump();
}

public class Foo
{ 
	public int Id { get; set; }
	public SqlHierarchyId Path { get; set; }
	
}
```

![image](https://user-images.githubusercontent.com/5913008/72857534-45143500-3c94-11ea-8134-27d6acfb4668.png)

Any specific scenario that is not functioning properly?

**Comment by yegor-n-a** [comment]
@Jaxelr I apologize for the late reply. I was a bit overloaded with other tasks.

Unfortunately, I am unable reproduce your successful try.

My setup:
`using Insight.Database;
using Microsoft.SqlServer.Types;
using System.Data.SqlClient;

namespace SqlHierarchyTesting
{
    class Program
    {
        static void Main(string[] args)
        {
            SqlInsightDbProvider.RegisterProvider();

            using (var conn = new SqlConnection(MyExtensions.SqlConnectionString))
            {
                var response = conn.QuerySql<Foo>("select 3 as [Id], hierarchyid::Parse('/1/2/3/') as [Path]");
            }
        }

        public class Foo
        {
            public int Id { get; set; }
            public SqlHierarchyId Path { get; set; }
        }
    }
}
`

**Comment by Jaxelr** [comment]
The only difference that i see from my version and your version, is that i used `Microsoft.SqlServer.Types`

![image](https://user-images.githubusercontent.com/5913008/75606818-0f4e4180-5ac7-11ea-8a43-cf0ff1661b86.png)

and these were the using libs

![image](https://user-images.githubusercontent.com/5913008/75606824-1ffeb780-5ac7-11ea-83a2-3f5be6109b1c.png)

**Comment by Jaxelr** [comment]
As i bet you could guess, the issue is the `dotMorten.Microsoft.SqlServer.Types` is not included as part of insight.database, and currently, there is no netstandard implementation of Microsoft.SqlServer.Types, there is an issue [open here](https://github.com/dotnet/SqlClient/issues/30), which we could track.

**Comment by jonwagner** [comment]
Note that custom sql types work properly in `net4x` implementations.

I spent some time working on the `netstandard` implementations but didn't get that far yesterday.

This is the first I'm seeing the `dotmorten` code. We may be able to use that as a bridge for now. Will take another look at it.

**Comment by jonwagner** [comment]
It looks like dotmorten doesn't work with the new Microsoft.Data.SqlClient driver.

See https://github.com/dotMorten/Microsoft.SqlServer.Types/issues/29

The main issue with these sqltypes is that the Sql driver does some special serialization on parameterization/recordset. It's automatic as long as the libraries can be loaded. However those libraries aren't portable yet.

We'll keep this open and watch the .NET core support for the standard types.

**Comment by box-robbie** [comment]
Now there is a dotMorten.Microsoft.SqlServer.Types v2.x : Depends on updated Microsoft.Data.SqlClient package.
See https://github.com/dotMorten/Microsoft.SqlServer.Types

**Problem**
When doing a select query containing a geography db field and having a DTO containing a SqlGeography property this throws an exception (see below).

Can you please help me. Do you have a solution for this problem? Can you make Insight.Database compitable with dotMorten.Microsoft.SqlServer.Types (v2.x)? 

This problem probably relates to: https://github.com/jonwagner/Insight.Database/issues/414

**Exception**
`  Message: 
*** threw exception: 
System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.Type'.

  Stack Trace: 
ColumnInfo.FromDataReader(IDataReader reader)
DbReaderDeserializer.GetDeserializer(IDataReader reader, Type type, IRecordStructure structure, SchemaMappingType mappingType)
DbReaderDeserializer.GetDeserializer[T](IDataReader reader, IRecordStructure structure)
OneToOne`1.GetRecordReader(IDataReader reader)
<AsEnumerable>d__3`1.MoveNext()
List`1.ctor(IEnumerable`1 collection)
Enumerable.ToList[TSource](IEnumerable`1 source)
DBReaderExtensions.ToList[T](IDataReader reader, IRecordReader`1 recordReader)
ListReader`1.Read(IDbCommand command, IDataReader reader)
<>c__DisplayClass178_0`1.<Query>b__1(IDbCommand cmd, IDataReader r)
DBConnectionExtensions.ExecuteAndAutoClose[T](IDbConnection connection, Func`2 getCommand, Func`3 translate, CommandBehavior commandBehavior)
DBConnectionExtensions.Query[T](IDbConnection connection, String sql, Object parameters, IQueryReader`1 returns, CommandType commandType, CommandBehavior commandBehavior, Nullable`1 commandTimeout, IDbTransaction transaction, Object outputParameters)
DBConnectionExtensions.QuerySql[T1](IDbConnection connection, String sql, Object parameters, CommandBehavior commandBehavior, Nullable`1 commandTimeout, IDbTransaction transaction, Object outputParameters)`

**References**
- Insight.Database: 6.3.9
- dotMorten.Microsoft.SqlServer.Types: 2.5.0
