### ISSUE TITLE
Fix the typo (broken link) for Building.md in the Wiki

### ISSUE THREAD

**Issue by rhtpandeyIN** [jonwagner/Insight.Database#419]
# Describe the bug

Typo (Documentation error)

## Steps to reproduce
Check this page
https://github.com/jonwagner/Insight.Database/wiki/Working-with-the-Code

## Expected behavior

I think it should redirect to this link :  https://github.com/jonwagner/Insight.Database/blob/master/Building.md

**Comment by rhtpandeyIN** [comment]
BTW, I tried to fix that by myself but I don't have permission to push here, and I couldn't see any repo for the Wiki in the author's profile, thus opening a Documentation bug here.

**Comment by Jaxelr** [comment]
Thanks for this issue, i fixed the link to the correct markdown file.

**Comment by rhtpandeyIN** [comment]
Thanks, it is working now :)
