### ISSUE TITLE
Unable to get started with docker.

### ISSUE THREAD

**Issue by rhtpandeyIN** [jonwagner/Insight.Database#421]
# Describe the question
docker-compose up is giving authentication error.

## Steps to reproduce (if applicable)

Rohit:Insight.Database Rohit$ cd insight-docker/
Rohit:insight-docker Rohit$ ls
Dockerfile.db2		docker-env.bat
docker-compose.yml	docker-env.sh
Rohit:insight-docker Rohit$ source docker-env.sh
127.0.0.1
Insight!!!Test
Insight docker environment variables set
'Rohit:insight-docker Rohit$ docker-compose up
 
Pulling sqlserver (microsoft/mssql-server-linux:)...
ERROR: Get https://registry-1.docker.io/v2/microsoft/mssql-server-linux/manifests/latest: unauthorized: incorrect username or password

Platform : macOS

Please help.

**Comment by rhtpandeyIN** [comment]
Sorry for the issue, I found the solution for this problem.

The cause was - I was logged in with the older deactivated docker id in my docker desktop. 

Closing this issue as it was not related to this library.

**Comment by rhtpandeyIN** [comment]
Eventually failing with DB2 now:

Rohit:insight-docker Rohit$ docker-compose up
Building db2
Step 1/7 : FROM ibmcom/db2express-c:latest
ERROR: Service 'db2' failed to build: pull access denied for ibmcom/db2express-c, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Please suggest.

**Comment by jonwagner** [comment]
IBM moved its docker image. I've updated the master branch to use the lastest DB2 docker image.
