### ISSUE TITLE
Consider implementing Stale probot on the repo

### ISSUE THREAD

**Issue by Jaxelr** [jonwagner/Insight.Database#425]
# Describe the feature

Consider the implementation of a Stale probot in order to help out with older issues, heres the marketplace link: https://probot.github.io/apps/stale/

## Is this feature related to a problem, describe

When issues stale in usage, they require manual intervention in order to close them.

## Additional context

As i understand it, it only requires a stale.yml file on the .github folder.

**Comment by jonwagner** [comment]
Good idea. Done.
