### ISSUE TITLE
Library Update Work ~Feb 8, 2020

### ISSUE THREAD

**Issue by jonwagner** [jonwagner/Insight.Database#431]
I blocked off some time next Saturday to make a pass through open issues.

I'll likely proceed in this order:

1. Fixed that have merge-ready code
2. New SQLServer driver - whatever Jaxel has ready
3. Easy bug fixes and asks
4. Hard stuff

If you've started working on an open issue, please assign it to yourself so I don't duplicate your effort. If there's something that impacts you, please make sure there is enough detail to reproduce the issue. I'm not likely to get a bunch of days in a row to diagnose things.

I'll kick out a new build if we get the open issue count low.

**Comment by lawrencek76** [comment]
If you get time to look at the hard stuff look at old issue #332, I have run into this myself but not looked at what it will take to address.

**Comment by jonwagner** [comment]
Sorry for the delay here. I got totally engulfed by coronavirus response work. I'll be looking for an upcoming opportunity to make a new build.

**Comment by jggutierrez** [comment]
Is there any update to this?  I know there's obviously a lot going on right now and I hope your situation is ok.  Just wondering if the Microsoft.Data.SqlClient support is still on the horizon?

**Comment by jonwagner** [comment]
I merged all of the open pull requests and tests are passing. Next step is to run through open issues and see if there's anything else to take care of before a build.

**Comment by jonwagner** [comment]
v6.3 is out.

For .netstandard2.0 and net46, the default package includes both the System.Data.SqlClient and Microsoft.Data.SqlClient providers for simplicity.

I don't *think* that's an issue, but if it is, I'll drop another build that splits that up. In the meantime, you can always pick and choose the packages that you want if you want/need to strip out either of the clients.
