### ISSUE TITLE
Join Insight Database to DotNetFoundation.org

### ISSUE THREAD

**Issue by keerthiraja1988** [jonwagner/Insight.Database#442]
This not specific to issues or bug.

Please join Insight.Database to DotNetFoundation (https://dotnetfoundation.org/). 

Joining form for projects : https://dotnetfoundation.org/projects/submit

https://dotnetfoundation.org/projects

**Comment by andymac4182** [comment]
@keerthiraja1988 What is the benefit for you for the project to join?

**Comment by jonwagner** [comment]
I could see taking advantage of the CI pipeline and code signing, but I doubt I'll make time for getting that set up. If there are volunteers willing to tackle it, I wouldn't object.
