### ISSUE TITLE
System.PlatformNotSupportedException: Strings.PlatformNotSupported_DataSqlClient in .NET 5

### ISSUE THREAD

**Issue by Orcomp** [jonwagner/Insight.Database#453]
# Describe the bug

We've updated Insight.Database to version 6.3.4 to run on .NET 5.

Exception is thrown when we try and create a new  sqlConnection.

## Steps to reproduce

When we try and connect to the database we get the System.PlatformNotSupportedException exception.

[PlatformNotSupportedException] System.PlatformNotSupportedException: Strings.PlatformNotSupported_DataSqlClient
   at Microsoft.Data.SqlClient.SqlConnection..ctor(String connectionString)

## Expected behavior

Was running fine in version 6.2.8 on .NET 4.7.2

- Dotnet version: net5.0-windows
- Database: SQL Server 11.0
- Library version: 6.3.4

**Comment by Orcomp** [comment]
Dug a bit deeper and it looks like Insight.Database.Providers.MsSqlClient is referencing a really old version of Microsoft.Data.SqlClient

![image](https://user-images.githubusercontent.com/2459973/109597995-7421f900-7b6c-11eb-8429-32fdb7df15ea.png)

![image](https://user-images.githubusercontent.com/2459973/109598083-a9c6e200-7b6c-11eb-9d3b-e681d75ec23f.png)

**Comment by Orcomp** [comment]
This may be somewhat related:

https://github.com/dotnet/SqlClient/issues/812
https://github.com/dotnet/SqlClient/issues/652#issuecomment-731615294

Unfortunately explicitly referencing Microsoft.Data.SqlClient 2.1.1 did not work for me.

**Comment by Jaxelr** [comment]
Could you post a minimal reproduction of the issue at hand? 

I made a tiny console app using v6.3.4 targeting net 5.0 https://github.com/Jaxelr/InsightNet50MsConsoleSample and it works correctly for a simple query execution.

**Comment by Orcomp** [comment]
Sorry for the false alarm. It took a bit of investigating to realise the issue was on our end. We are embedding Insight.Database into a plugin using Costura, and didn't include the runtime. Now that we have, It is all working properly. Will close the issue.

**Comment by greivinarr** [comment]
I use Winforms, WPF and Console app in .net5 with ADO.net System.Data with no problems...; but when link to ASP.net core, throws System.PlatformNotSupportedException error... in both namespaces "System.Data" and "Microsoft.data"...

**Comment by Orcomp** [comment]
@greivinarr  make sure you are using the correct libraries and runtimes versions. You are probably referencing an (old) .NET framework library somewhere.
