### ISSUE TITLE
Is there an "Insight.Database" style package in javascript/typescript world?

### ISSUE THREAD

**Issue by ThisNoName** [jonwagner/Insight.Database#458]
I might be obligated to do stuff in Node.Js, but kind of stuck on ORM.  Not that there aren't enough wonderful frameworks already, but once you got pampered by Insight auto interface, everything else is just like WTH?!  Suggestions?

**Comment by jonwagner** [comment]
:) not that I know of... I don't think it would be hard. JS/Typescript is really flexible so a lot of the conversion code wouldn't be necessary. I think there is enough introspection in JS to similar functionality.
