### ISSUE TITLE
Support complex objects mapping

### ISSUE THREAD

**Issue by ezelans** [jonwagner/Insight.Database#462]
I have a complex object like this:
Request
{
        double Id {get; set;}
        Language language {get; set;}
        ILIst<WebSite> WebSites {get; set;} 
}

On my repository I have this method:
GetSarasa(){
       GetSqlConnection().QuerySqlAsync("SELECT * FROM Request INNER JOIN Language ON (...) INNER JOIN Website ON (...)
       WHERE (...),
       Parameters.Empty,
       Query.Returns(Together<Request, WebSite>.Records)).ConfigureAwait(false)
}

And that method returns me Request with WebSites but I can't figure it out how to get the Language too.

Can you help me pls?

- Dotnet version: [netcore5]
- Database: [SQL Server]
- Library version: [6.2.3]

**Comment by Jaxelr** [comment]
An alternative is to use 
`Query.Returns(OneToOne<Request, Language>.Records).ThenChildren(Some<Websites>.Records))`

But it will require that your query returns 2 result sets, something like:

```sql 
SELECT * FROM Request INNER JOIN Language ON (...);

SELECT RequestId, * FROM Request INNER JOIN Website ON (...);
```

You can check in the [wiki](https://github.com/jonwagner/Insight.Database/wiki/Specifying-Result-Structures#mixing-and-matching) for the rules of mapping to parents

**Comment by ezelans** [comment]
Yhea.... but I dont want to return 2 result set. I think that should be any way to fill an entire object with a single query.

**Comment by jonwagner** [comment]
First test with the latest build. The 6.3 series had a few items that support similar cases.

On Jul 8, 2021, at 9:37 AM, Ezequiel ***@***.***> wrote:

﻿

Yhea.... but I dont want to return 2 result set. I think that should be any way to fill an entire object with a single query.

**Comment by ezelans** [comment]
Thanks !
