### ISSUE TITLE
Unit test with Moq 

### ISSUE THREAD

**Issue by ezelans** [jonwagner/Insight.Database#463]
# Describe the question

I'm trying to create some unit test without connect with the database. 

So I have this method:

public async Task GetCountry(countryId){
     await  GetSQLConnection().QueryAsync<Country>("GetCountry", new {@CountryId = countryId}).ConfigureAwait(false)
};

Can you help me to test this method?

**Comment by Jaxelr** [comment]
What type of error message are you getting?

Please also provide the SQLs related to the method (stored procedures, tables)

**Comment by jonwagner** [comment]
The only thing the method does is connect to the database and return data. I don't think you can easily test that without mocking the entire database functionality. In my opinion, you're not getting much test value out of testing that scenario.

If you really wanted to test this with Moq, you would need to:

1. Have GetSQLConnection() return a mock SqlConnection.
2. Have that mock return a mock Task<recordset> for QueryAsync. It should behave like a task when you call configure await.
3. Have that mock task return a mock recordset that contained the data that you are mapping.

At that point, it would return the data to Insight.Database to be mapped to a data structure. That code is already tested and unlikely to change.

A more valuable test scenario would be to use the repository pattern with InsightDB:

```
interface ICountryRepository {
    Task<Country> GetCountry(int countryId);
}

```
// use the repository with:
var repo = sqlConnection.As<ICountryRepository>()
var list = repo.GetCountry(id);

// mock the repository with:
var mock = new Moq<ICountryRepository>();
mock.(setup the GetCountry response)
var repo = mock.Object;
```

Then you're not testing the boilerplate code. You're testing how your code uses it.

**Comment by jonwagner** [comment]
In 6.3.9, the Results constructors are now public:

```
            var results = new Results<int, int>(new List<int>() { 1, 2 }, new List<int>() { 3, 4 });
```

As a reminder, the more detail you provide on an issue, the faster we can resolve it.
