### ISSUE TITLE
SQLConstructor using invalid value

### ISSUE THREAD

**Issue by delossan** [jonwagner/Insight.Database#467]
Tablename:  package

|id|title|packageId|
|---|---|---|
|122|title1|102102|

SQL statement: **select * from package**
```
[SqlConstructor]
    public Package(int id, string title, int packageId)
        : base(id, title, packageId){}
```
I put a breakpoint on the sqlconstructor and the value for packageId is 1.  Any idea why I'm getting a different value instead of the expected value of 102102?

**Comment by jonwagner** [comment]
/shrug nothing obvious. should just work.

can you create a branch with a test case that reproduces it? then we can hop in and debug.

**Comment by delossan** [comment]
Made a change to set the int packageId from nullable to not nullable and it is now working as expected.

**Comment by jonwagner** [comment]
What is your whole class? Was the packageId in the object an `int?` but the one in the constructor an `int`
