### ISSUE TITLE
Log auto mapped stored proc input parameters

### ISSUE THREAD

**Issue by raidken** [jonwagner/Insight.Database#472]
# Describe the question

How can I get a handle over the the parameter values mapped for any stored procedure or SQL call. I want to log the mapped parameter 

public interface IProductRepo
{
 [Sql("[spGetSimilarProducts]")]
 IList<Products> GetSimilarProducts(Product product);
}
Product product = new Product(){ ..... };
productRepo.GetSimilarProducts(product);
//How do I get the actual parameter bound to the call the stored proc?

## Steps to reproduce (if applicable)

- Dotnet version: [netcore2, dotnet472]
- Database: [SQL Server, Oracle, MySQL]
- Library version: [6.2.3]

**Comment by jonwagner** [comment]
I'm not sure what you're trying to do.

If you are trying to log your database calls, I'd recommend a logging proxy (EventSourceProxy or something based on castle).

If you are trying to diagnose mapping problems, there's probably an easier way to solve the problem if you post more information.

**Comment by raidken** [comment]
I need to log database calls along with the parameters passed  in the database calls.
