### ISSUE TITLE
Update library to reference latest version of Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by psiservices-ketan-javia** [jonwagner/Insight.Database#473]
# Describe the feature

Insight.Database.Providers.MsSqlClient project is using a pretty outdated 
`<PackageReference Include="Microsoft.Data.SqlClient" Version="1.1.0" />` 

## Is this feature related to a problem, describe
This is preventing us from using handy features like `Command Timeout` in connection string which is available since v2.1

**Comment by Jaxelr** [comment]
Considering that Insight.Database.Providers.MsSqlClient library has a target fx of net46, we will have to update it to version 2.1.4 to maintain fxcompat.

**Comment by jonwagner** [comment]
:+1: we can update and do a build. Note that the providers are forward-compatible so if you want to use a newer driver you can just upgrade your own project.
