### ISSUE TITLE
Cannot derive parameters for the stored procedure X. Have you loaded the provider that supports SqlCommand?

### ISSUE THREAD

**Issue by jesserizzo** [jonwagner/Insight.Database#478]
# Describe the bug
Created a new Azure Function project in an existing sln. Insight works fine in the API project, but fails when called from the Function App with the message
`Cannot derive parameters for the stored procedure GetEmployerPaidStatus. Have you loaded the provider that supports SqlCommand?`

## Steps to reproduce
Create a new timer triggered Azure function (`func init` and `func new` commands)
Run the following code
```using System;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Host;
using Microsoft.Extensions.Logging;
using System.Data.Common;
using Microsoft.Data.SqlClient;
using Insight.Database;

namespace temp
{
    public class Test
    {
        [FunctionName("Test")]
        public void Run([TimerTrigger("0 */1 * * * *", RunOnStartup = true)] TimerInfo myTimer, ILogger log)
        {
            SqlInsightDbProvider.RegisterProvider();
            DbConnection connection = new SqlConnection("valid connection string");
            TestRepository repository = connection.As<TestRepository>();
            repository.StoredProcedureName();
            log.LogInformation($"C# Timer trigger function executed at: {DateTime.Now}");
        }
    }

    public interface TestRepository
    {
        public bool StoredProcedureName();
    }
}
```

## Expected behavior

Insight should be able to call the stored procedure

- Dotnet version: [Dotnet 6]
- Database: [SQL Server]
- Library version: [6.3.10]

**Comment by jesserizzo** [comment]
Ok this is fixed now, I needed to call
`Insight.Database.Providers.MsSqlClient.SqlInsightDbProvider.RegisterProvider();`

**Comment by MikePreston17** [comment]
> Ok this is fixed now, I needed to call `Insight.Database.Providers.MsSqlClient.SqlInsightDbProvider.RegisterProvider();`

Right, but where, exactly?

**Comment by Jaxelr** [comment]
Anywhere before it interacts with the Db should be fine. See this [wiki](https://github.com/jonwagner/Insight.Database/wiki/Installing-Insight)
