### ISSUE TITLE
Release 6.3.11 has wrong git tag

### ISSUE THREAD

**Issue by sharpjs** [jonwagner/Insight.Database#491]
# Describe the bug

Release 6.3.11 is tagged [6.3.13](https://github.com/jonwagner/Insight.Database/releases/tag/6.3.13).

## Steps to reproduce

Click link above.

## Expected behavior

The git tag should be 6.3.11 is [6.3.11](https://github.com/jonwagner/Insight.Database/releases/tag/6.3.11).

- Dotnet version: all of them
- Database: all of them
- Library version: all of them

**Comment by jonwagner** [comment]
got it. thanks!
