### ISSUE TITLE
BulkCopy is not working with MySqlConnector

### ISSUE THREAD

**Issue by elandev** [jonwagner/Insight.Database#492]
# Describe the bug
`MySqlBulkdLoader `is working, but when I attempt to use the method `connection.BulkCopy` with a list, I get the following exception:

> MySqlConnector.MySqlException: 'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '0 * FROM TestInsight;
> SET sql_select_limit=default' at line 1'

## Steps to reproduce
1. Load the attached project with Visual Studio 2022.
2. Set up MariaDB as the database (10.11.2-MariaDB).
3. Edit the server, database name and credentials for the connection string.
4. Restore Nuget packages and build the solution.
5. Run the project.

The method `BulkLoadDataMySql`, which uses `MySqlBulkLoader `works.

The method `BulkLoadDataInsight `does not work and you will see the exception.

## Expected behavior
Expected the bulk copy to insert all items in the list.

- Dotnet version: 6.0
- Database: 10.11.2-MariaDB
- Library version: Insight 6.3.11
[TestMySqlBulkLoad.zip](https://github.com/jonwagner/Insight.Database/files/11069000/TestMySqlBulkLoad.zip)

**Comment by jonwagner** [comment]
Unfortunately, we can't accept project zip files as reproduction cases. Please paste sufficient code to reproduce here, or submit a PR with a failing test case.
