### ISSUE TITLE
Could not load type 'SqlGuidCaster' from assembly 'System.Data.SqlClient, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' because it contains an object field at offset 0 that is incorrectly aligned or overlapped by a non-object field.

### ISSUE THREAD

**Issue by m0hamdan** [jonwagner/Insight.Database#507]
# Describe the bug

I've upgraded **Insight.Database** to version **6.3.11** and I've noticed this version is referencing a vulnerable version of  System.Data.SqlClient (4.5.0), which is causing the below error upon upgrading to .NET 8.

`Could not load type 'SqlGuidCaster' from assembly 'System.Data.SqlClient, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' because it contains an object field at offset 0 that is incorrectly aligned or overlapped by a non-object field.`

 Could you please upgrade to the latest version or better yet replace it with **Microsoft.Data.SqlClient** thanks

## Steps to reproduce

1- Create a .NET 8 project
2- Install the latest version of Insight.Database
3- Run AppDomain.CurrentDomain.GetAssemblies()
            .SelectMany(assembly => assembly.GetTypes())
            .Where(type => !type.IsAbstract && typeof(T).IsAssignableFrom(type))
            .Select(type => type.Assembly)
            .Distinct()
## Expected behavior

- Dotnet version: [dotnet8]
- Database: [SQL Server]
- Library version: [6.3.11]
![Insight Database](https://github.com/jonwagner/Insight.Database/assets/29398560/cab01caf-a11e-412d-90c1-3530de43183d)

**Comment by MoeHamdan** [comment]
https://github.com/dotnet/SqlClient/issues/1930

The package needs to be upgraded

**Comment by MoeHamdan** [comment]
@jonwagner may you please upgrade to support .net 8?

**Comment by jonwagner** [comment]
working on this now...

**Comment by jonwagner** [comment]
The `upgrade8` branch has everything running under .NET8. I'll spend the next day or two going through open issues then I'll do a formal build.

**Comment by m0hamdan** [comment]
Thank you @jonwagner , much appreciated!
