### ISSUE TITLE
Support for dotnet framework4.8

### ISSUE THREAD

**Issue by Daniel12321** [jonwagner/Insight.Database#517]
We are using Insight Database in a dotnet4.8 framework project. Is it possible to get support for this version in 8.0.1 and up?

- Dotnet version: [dotnet framework 4.8]
- Database: [SQL Server]
- Library version: [8.0.1]

**Comment by jonwagner** [comment]
Ah - I didn't realize that Microsoft was keeping net48 alive with versions of the Windows OS.

Unfortunately, I currently don't have regular access to a Windows machine for builds, so it will take me some time to get that set up again. But Insight v6 and v8 are mostly identical so you can use that for now.

**Comment by jfrank14** [comment]
+1 for this. I'm using .net framework 4.8 as well and nuget is nagging me to upgrade but I can't, because of this issue.

**Comment by jonwagner** [comment]
I'm going to try this to clean up the build process:

https://stu.dev/dotnet-framework-reference-assemblies-via-nuget/

**Comment by jonwagner** [comment]
@jfrank14 @Daniel12321 

can one of you try the build off of this branch:

https://github.com/jonwagner/Insight.Database/compare/net48

**Comment by jfrank14** [comment]
I checked out this branch and it built successfully. Was there anything else you wanted to know about the build?

**Comment by jonwagner** [comment]
I know the branch builds but I don't have a .net 4.8 project to test it in. it would be great just to get a sanity check that it works there.

**Comment by jfrank14** [comment]
Is it enough to replace the Insight* files in the bin folder? The only way I know there's an issue is that NuGet won't let me upgrade, but to test _that_ would require publishing to NuGet.

**Comment by jonwagner** [comment]
Yeah probably

On Sep 12, 2024, at 4:38 PM, jfrank14 ***@***.***> wrote:

﻿

Is it enough to replace the Insight* files in the bin folder? The only way I know there's an issue is that NuGet won't let me upgrade, but to test that would require publishing to NuGet.

**Comment by jonwagner** [comment]
actually...I can do a prerelease build and you can test it.

**Comment by jonwagner** [comment]
ok... I pushed version 8.0.2-beta1. That should contain the net48 versions. LMK if that works and I'll convert it to a release build.

**Comment by jfrank14** [comment]
I just tried that beta version on a 4.8 project and it upgraded. I haven't tried to run it yet, because there are some other reference issues, but does knowing that NuGet worked answer enough of the question for you, or do you also want confirmation that it runs without error?

**Comment by jfrank14** [comment]
I just tried that beta version on a 4.8 project and it upgraded. I haven't tried to run it yet, because there are some other reference issues, but does knowing that NuGet worked answer enough of the question for you, or do you want confirmation that it runs without error?

**Comment by jonwagner** [comment]
released

**Comment by jfrank14** [comment]
Thanks! I really want to thank you for this wonderful software. I use it everywhere and it's a core bit of kit for me.
